# Update ogen.jsonschema.yml after editing this file.

# sets parser options.
parser:
  # enables type inference for schemas. Schema parser will try to detect schema type by its properties.
  infer_types: true
  #  enables remote references resolving. See https://github.com/ogen-go/ogen/issues/385.
  allow_remote: true
  # is maximum depth of schema generation. Default is 1000.
  depth_limit: 1000
  # allowed authentication schemes. See https://swagger.io/specification/#security-scheme-object.
  authentication_schemes:
    - 'basic'
    - 'Telegram'

# sets generator options.
generator:
  # sets generator features.
  features:
    enable:
      # Enables paths server generation
      - 'paths/server'
      # Enables validation of client requests
      - 'client/request/validation'
      # Enables validation of server responses
      - 'server/response/validation'
    disable_all: true

  # contains filters to skip operations.
  filters:
    path_regex: ".*"
    methods: ["GET", "POST", "PUT", "PATCH", "DELETE"]

  # functions to ignore
  ignore_not_implemented: ["all"]

# is a path to expanded spec.
expand: ""