// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package msgs

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"time"

	"go.uber.org/zap"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.getSavedMessageByIdStmt, err = db.PrepareContext(ctx, getSavedMessageById); err != nil {
		return nil, fmt.Errorf("error preparing query GetSavedMessageById: %w", err)
	}
	if q.insertRawUpdateStmt, err = db.PrepareContext(ctx, insertRawUpdate); err != nil {
		return nil, fmt.Errorf("error preparing query InsertRawUpdate: %w", err)
	}
	if q.insertSavedMessageStmt, err = db.PrepareContext(ctx, insertSavedMessage); err != nil {
		return nil, fmt.Errorf("error preparing query InsertSavedMessage: %w", err)
	}
	if q.listEditHistoryByMessageStmt, err = db.PrepareContext(ctx, listEditHistoryByMessage); err != nil {
		return nil, fmt.Errorf("error preparing query ListEditHistoryByMessage: %w", err)
	}
	if q.updateMessageTextStmt, err = db.PrepareContext(ctx, updateMessageText); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateMessageText: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.getSavedMessageByIdStmt != nil {
		if cerr := q.getSavedMessageByIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSavedMessageByIdStmt: %w", cerr)
		}
	}
	if q.insertRawUpdateStmt != nil {
		if cerr := q.insertRawUpdateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertRawUpdateStmt: %w", cerr)
		}
	}
	if q.insertSavedMessageStmt != nil {
		if cerr := q.insertSavedMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertSavedMessageStmt: %w", cerr)
		}
	}
	if q.listEditHistoryByMessageStmt != nil {
		if cerr := q.listEditHistoryByMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listEditHistoryByMessageStmt: %w", cerr)
		}
	}
	if q.updateMessageTextStmt != nil {
		if cerr := q.updateMessageTextStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateMessageTextStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                           DBTX
	logger                       *zap.Logger
	SlowQueryThreshold           time.Duration
	txID                         string
	tx                           *sql.Tx
	getSavedMessageByIdStmt      *sql.Stmt
	insertRawUpdateStmt          *sql.Stmt
	insertSavedMessageStmt       *sql.Stmt
	listEditHistoryByMessageStmt *sql.Stmt
	updateMessageTextStmt        *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                           tx,
		logger:                       q.logger,
		SlowQueryThreshold:           q.SlowQueryThreshold,
		txID:                         fmt.Sprintf("%p", tx),
		tx:                           tx,
		getSavedMessageByIdStmt:      q.getSavedMessageByIdStmt,
		insertRawUpdateStmt:          q.insertRawUpdateStmt,
		insertSavedMessageStmt:       q.insertSavedMessageStmt,
		listEditHistoryByMessageStmt: q.listEditHistoryByMessageStmt,
		updateMessageTextStmt:        q.updateMessageTextStmt,
	}
}

func (q *Queries) logQuery(query string, params []zap.Field, err error, start time.Time) {
	if q.logger == nil {
		return
	}

	duration := time.Since(start)
	fields := make([]zap.Field, 0, len(params)+4)
	fields = append(fields,
		zap.Time("ts", start),
		zap.String("sql", query),
	)
	if q.txID != "" {
		fields = append(fields, zap.String("txID", q.txID))
	}
	fields = append(fields, params...)
	fields = append(fields, zap.Duration("duration", duration))
	if err != nil {
		fields = append(fields, zap.Error(err))
	}

	if q.SlowQueryThreshold > 0 && duration > q.SlowQueryThreshold {
		q.logger.Warn("slow query", fields...)
		return
	}
	if err != nil && !errors.Is(err, sql.ErrNoRows) {
		q.logger.Error("query failed", fields...)
		return
	}
	q.logger.Info("query", fields...)
}

func zapNullString(key string, v sql.NullString) zap.Field {
	if v.Valid {
		return zap.String(key, v.String)
	}
	return zap.String(key, "<nil>")
}

func zapNullBool(key string, v sql.NullBool) zap.Field {
	if v.Valid {
		return zap.Bool(key, v.Bool)
	}
	return zap.String(key, "<nil>")
}

func zapNullInt32(key string, v sql.NullInt32) zap.Field {
	if v.Valid {
		return zap.Int32(key, v.Int32)
	}
	return zap.String(key, "<nil>")
}

func zapNullInt64(key string, v sql.NullInt64) zap.Field {
	if v.Valid {
		return zap.Int64(key, v.Int64)
	}
	return zap.String(key, "<nil>")
}

func zapNullFloat64(key string, v sql.NullFloat64) zap.Field {
	if v.Valid {
		return zap.Float64(key, v.Float64)
	}
	return zap.String(key, "<nil>")
}

func zapNullTime(key string, v sql.NullTime) zap.Field {
	if v.Valid {
		return zap.Time(key, v.Time)
	}
	return zap.String(key, "<nil>")
}
