// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package msgs

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type EditHistory struct {
	ChatID    int64  `json:"chat_id"`
	MessageID int64  `json:"message_id"`
	EditID    int64  `json:"edit_id"`
	Text      string `json:"text"`
}

type RawUpdate struct {
	ID        int64       `json:"id"`
	ChatID    pgtype.Int8 `json:"chat_id"`
	MessageID pgtype.Int8 `json:"message_id"`
	RawUpdate []byte      `json:"raw_update"`
}

type SavedMsg struct {
	MessageID         int64              `json:"message_id"`
	ChatID            int64              `json:"chat_id"`
	FromUserID        pgtype.Int8        `json:"from_user_id"`
	SenderChatID      pgtype.Int8        `json:"sender_chat_id"`
	Date              pgtype.Timestamptz `json:"date"`
	ForwardOriginName pgtype.Text        `json:"forward_origin_name"`
	ForwardOriginID   pgtype.Int8        `json:"forward_origin_id"`
	MessageThreadID   pgtype.Int8        `json:"message_thread_id"`
	ReplyToMessageID  pgtype.Int8        `json:"reply_to_message_id"`
	ReplyToChatID     pgtype.Int8        `json:"reply_to_chat_id"`
	ViaBotID          pgtype.Int8        `json:"via_bot_id"`
	EditDate          pgtype.Timestamptz `json:"edit_date"`
	MediaGroupID      pgtype.Text        `json:"media_group_id"`
	Text              pgtype.Text        `json:"text"`
	EntitiesJson      []byte             `json:"entities_json"`
	MediaID           pgtype.Text        `json:"media_id"`
	MediaUid          pgtype.Text        `json:"media_uid"`
	MediaType         pgtype.Text        `json:"media_type"`
	ExtraData         []byte             `json:"extra_data"`
	ExtraType         pgtype.Text        `json:"extra_type"`
}
