// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package msgs

import (
	"database/sql"
)

type EditHistory struct {
	ChatID    int64  `json:"chat_id"`
	MessageID int64  `json:"message_id"`
	EditID    int64  `json:"edit_id"`
	Text      string `json:"text"`
}

type RawUpdate struct {
	ID        int64         `json:"id"`
	ChatID    sql.NullInt64 `json:"chat_id"`
	MessageID sql.NullInt64 `json:"message_id"`
	RawUpdate interface{}   `json:"raw_update"`
}

type SavedMsg struct {
	MessageID         int64          `json:"message_id"`
	ChatID            int64          `json:"chat_id"`
	FromUserID        sql.NullInt64  `json:"from_user_id"`
	SenderChatID      sql.NullInt64  `json:"sender_chat_id"`
	Date              UnixTime       `json:"date"`
	ForwardOriginName sql.NullString `json:"forward_origin_name"`
	ForwardOriginID   sql.NullInt64  `json:"forward_origin_id"`
	MessageThreadID   sql.NullInt64  `json:"message_thread_id"`
	ReplyToMessageID  sql.NullInt64  `json:"reply_to_message_id"`
	ReplyToChatID     sql.NullInt64  `json:"reply_to_chat_id"`
	ViaBotID          sql.NullInt64  `json:"via_bot_id"`
	EditDate          interface{}    `json:"edit_date"`
	MediaGroupID      sql.NullString `json:"media_group_id"`
	Text              sql.NullString `json:"text"`
	EntitiesJson      interface{}    `json:"entities_json"`
	MediaID           sql.NullString `json:"media_id"`
	MediaUid          sql.NullString `json:"media_uid"`
	MediaType         sql.NullString `json:"media_type"`
	ExtraData         interface{}    `json:"extra_data"`
	ExtraType         sql.NullString `json:"extra_type"`
}
