// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query_saved_msg.sql

package msgs

import (
	"context"
	"database/sql"
	"time"

	"go.uber.org/zap"
)

const createNewMessage = `-- name: CreateNewMessage :exec

INSERT INTO saved_msgs (message_id, chat_id, from_user_id, sender_chat_id, date, forward_origin_name, forward_origin_id,
                        message_thread_id, reply_to_message_id, reply_to_chat_id, via_bot_id, edit_date, media_group_id,
                        text, entities_json, media_id, media_uid, media_type, extra_data, extra_type)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateNewMessageParams struct {
	MessageID         int64          `json:"message_id"`
	ChatID            int64          `json:"chat_id"`
	FromUserID        sql.NullInt64  `json:"from_user_id"`
	SenderChatID      sql.NullInt64  `json:"sender_chat_id"`
	Date              UnixTime       `json:"date"`
	ForwardOriginName sql.NullString `json:"forward_origin_name"`
	ForwardOriginID   sql.NullInt64  `json:"forward_origin_id"`
	MessageThreadID   sql.NullInt64  `json:"message_thread_id"`
	ReplyToMessageID  sql.NullInt64  `json:"reply_to_message_id"`
	ReplyToChatID     sql.NullInt64  `json:"reply_to_chat_id"`
	ViaBotID          sql.NullInt64  `json:"via_bot_id"`
	EditDate          interface{}    `json:"edit_date"`
	MediaGroupID      sql.NullString `json:"media_group_id"`
	Text              sql.NullString `json:"text"`
	EntitiesJson      interface{}    `json:"entities_json"`
	MediaID           sql.NullString `json:"media_id"`
	MediaUid          sql.NullString `json:"media_uid"`
	MediaType         sql.NullString `json:"media_type"`
	ExtraData         interface{}    `json:"extra_data"`
	ExtraType         sql.NullString `json:"extra_type"`
}

// encoding: utf-8
func (q *Queries) CreateNewMessage(ctx context.Context, arg CreateNewMessageParams) error {
	var logFields []zap.Field
	var start time.Time
	if q.logger != nil {
		logFields = make([]zap.Field, 0, 20+5)
		start = time.Now()
		logFields = append(logFields,
			zap.Int64("message_id", arg.MessageID),
			zap.Int64("chat_id", arg.ChatID),
			zapNullInt64("from_user_id", arg.FromUserID),
			zapNullInt64("sender_chat_id", arg.SenderChatID),
			zap.Any("date", arg.Date),
			zapNullString("forward_origin_name", arg.ForwardOriginName),
			zapNullInt64("forward_origin_id", arg.ForwardOriginID),
			zapNullInt64("message_thread_id", arg.MessageThreadID),
			zapNullInt64("reply_to_message_id", arg.ReplyToMessageID),
			zapNullInt64("reply_to_chat_id", arg.ReplyToChatID),
			zapNullInt64("via_bot_id", arg.ViaBotID),
			zap.Any("edit_date", arg.EditDate),
			zapNullString("media_group_id", arg.MediaGroupID),
			zapNullString("text", arg.Text),
			zap.Any("entities_json", arg.EntitiesJson),
			zapNullString("media_id", arg.MediaID),
			zapNullString("media_uid", arg.MediaUid),
			zapNullString("media_type", arg.MediaType),
			zap.Any("extra_data", arg.ExtraData),
			zapNullString("extra_type", arg.ExtraType),
		)
	}
	_, err := q.exec(ctx, q.createNewMessageStmt, createNewMessage,
		arg.MessageID,
		arg.ChatID,
		arg.FromUserID,
		arg.SenderChatID,
		arg.Date,
		arg.ForwardOriginName,
		arg.ForwardOriginID,
		arg.MessageThreadID,
		arg.ReplyToMessageID,
		arg.ReplyToChatID,
		arg.ViaBotID,
		arg.EditDate,
		arg.MediaGroupID,
		arg.Text,
		arg.EntitiesJson,
		arg.MediaID,
		arg.MediaUid,
		arg.MediaType,
		arg.ExtraData,
		arg.ExtraType,
	)
	q.logQuery(createNewMessage, logFields, err, start)
	return err
}

const getSavedMessageById = `-- name: GetSavedMessageById :one
SELECT message_id, chat_id, from_user_id, sender_chat_id, date, forward_origin_name, forward_origin_id, message_thread_id, reply_to_message_id, reply_to_chat_id, via_bot_id, edit_date, media_group_id, text, entities_json, media_id, media_uid, media_type, extra_data, extra_type
FROM saved_msgs
WHERE chat_id = ?
  AND message_id = ?
`

func (q *Queries) GetSavedMessageById(ctx context.Context, chatID int64, messageID int64) (SavedMsg, error) {
	var logFields []zap.Field
	var start time.Time
	if q.logger != nil {
		logFields = make([]zap.Field, 0, 2+5)
		start = time.Now()
		logFields = append(logFields,
			zap.Int64("chat_id", chatID),
			zap.Int64("message_id", messageID),
		)
	}
	row := q.queryRow(ctx, q.getSavedMessageByIdStmt, getSavedMessageById, chatID, messageID)
	var i SavedMsg
	err := row.Scan(
		&i.MessageID,
		&i.ChatID,
		&i.FromUserID,
		&i.SenderChatID,
		&i.Date,
		&i.ForwardOriginName,
		&i.ForwardOriginID,
		&i.MessageThreadID,
		&i.ReplyToMessageID,
		&i.ReplyToChatID,
		&i.ViaBotID,
		&i.EditDate,
		&i.MediaGroupID,
		&i.Text,
		&i.EntitiesJson,
		&i.MediaID,
		&i.MediaUid,
		&i.MediaType,
		&i.ExtraData,
		&i.ExtraType,
	)
	q.logQuery(getSavedMessageById, logFields, err, start)
	return i, err
}

const updateMessageText = `-- name: UpdateMessageText :exec
UPDATE saved_msgs
SET text=?
WHERE chat_id = ?
  AND message_id = ?
`

func (q *Queries) UpdateMessageText(ctx context.Context, text sql.NullString, chatID int64, messageID int64) error {
	var logFields []zap.Field
	var start time.Time
	if q.logger != nil {
		logFields = make([]zap.Field, 0, 3+5)
		start = time.Now()
		logFields = append(logFields,
			zapNullString("text", text),
			zap.Int64("chat_id", chatID),
			zap.Int64("message_id", messageID),
		)
	}
	_, err := q.exec(ctx, q.updateMessageTextStmt, updateMessageText, text, chatID, messageID)
	q.logQuery(updateMessageText, logFields, err, start)
	return err
}
