// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query_saved_msg.sql

package msgs

import (
	"context"
	"database/sql"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSavedMessageById = `-- name: GetSavedMessageById :one
SELECT message_id,
       chat_id,
       from_user_id,
       sender_chat_id,
       date,
       forward_origin_name,
       forward_origin_id,
       message_thread_id,
       reply_to_message_id,
       reply_to_chat_id,
       via_bot_id,
       edit_date,
       media_group_id,
       text,
       entities_json,
       media_id,
       media_uid,
       media_type,
       extra_data,
       extra_type
FROM saved_msgs
WHERE chat_id = $1
  AND message_id = $2
`

func (q *Queries) GetSavedMessageById(ctx context.Context, chatID int64, messageID int64) (SavedMsg, error) {
	row := q.db.QueryRow(ctx, getSavedMessageById, chatID, messageID)
	var i SavedMsg
	err := row.Scan(
		&i.MessageID,
		&i.ChatID,
		&i.FromUserID,
		&i.SenderChatID,
		&i.Date,
		&i.ForwardOriginName,
		&i.ForwardOriginID,
		&i.MessageThreadID,
		&i.ReplyToMessageID,
		&i.ReplyToChatID,
		&i.ViaBotID,
		&i.EditDate,
		&i.MediaGroupID,
		&i.Text,
		&i.EntitiesJson,
		&i.MediaID,
		&i.MediaUid,
		&i.MediaType,
		&i.ExtraData,
		&i.ExtraType,
	)
	return i, err
}

const insertRawUpdate = `-- name: InsertRawUpdate :exec
INSERT INTO raw_update (chat_id, message_id, raw_update)
VALUES ($1, $2, $3)
`

func (q *Queries) InsertRawUpdate(ctx context.Context, chatID pgtype.Int8, messageID pgtype.Int8, rawUpdate []byte) error {
	_, err := q.db.Exec(ctx, insertRawUpdate, chatID, messageID, rawUpdate)
	return err
}

const insertSavedMessage = `-- name: InsertSavedMessage :exec

INSERT INTO saved_msgs (message_id, chat_id, from_user_id, sender_chat_id, date, forward_origin_name, forward_origin_id,
                        message_thread_id, reply_to_message_id, reply_to_chat_id, via_bot_id, edit_date, media_group_id,
                        text, entities_json, media_id, media_uid, media_type, extra_data, extra_type)
VALUES ($1, $2, $3, $4, $5,
        $6, $7, $8, $9, $10,
        $11, $12, $13, $14, $15,
        $16, $17, $18, $19, $20)
ON CONFLICT(chat_id, message_id) DO NOTHING
`

type InsertSavedMessageParams struct {
	MessageID         int64              `json:"message_id"`
	ChatID            int64              `json:"chat_id"`
	FromUserID        pgtype.Int8        `json:"from_user_id"`
	SenderChatID      pgtype.Int8        `json:"sender_chat_id"`
	Date              UnixTime           `json:"date"`
	ForwardOriginName sql.NullString     `json:"forward_origin_name"`
	ForwardOriginID   pgtype.Int8        `json:"forward_origin_id"`
	MessageThreadID   pgtype.Int8        `json:"message_thread_id"`
	ReplyToMessageID  pgtype.Int8        `json:"reply_to_message_id"`
	ReplyToChatID     pgtype.Int8        `json:"reply_to_chat_id"`
	ViaBotID          pgtype.Int8        `json:"via_bot_id"`
	EditDate          sql.Null[UnixTime] `json:"edit_date"`
	MediaGroupID      sql.NullString     `json:"media_group_id"`
	Text              sql.NullString     `json:"text"`
	EntitiesJson      []byte             `json:"entities_json"`
	MediaID           sql.NullString     `json:"media_id"`
	MediaUid          sql.NullString     `json:"media_uid"`
	MediaType         sql.NullString     `json:"media_type"`
	ExtraData         []byte             `json:"extra_data"`
	ExtraType         sql.NullString     `json:"extra_type"`
}

// encoding: utf-8
func (q *Queries) InsertSavedMessage(ctx context.Context, arg InsertSavedMessageParams) error {
	_, err := q.db.Exec(ctx, insertSavedMessage,
		arg.MessageID,
		arg.ChatID,
		arg.FromUserID,
		arg.SenderChatID,
		arg.Date,
		arg.ForwardOriginName,
		arg.ForwardOriginID,
		arg.MessageThreadID,
		arg.ReplyToMessageID,
		arg.ReplyToChatID,
		arg.ViaBotID,
		arg.EditDate,
		arg.MediaGroupID,
		arg.Text,
		arg.EntitiesJson,
		arg.MediaID,
		arg.MediaUid,
		arg.MediaType,
		arg.ExtraData,
		arg.ExtraType,
	)
	return err
}

const listEditHistoryByMessage = `-- name: ListEditHistoryByMessage :many
SELECT chat_id,
       message_id,
       edit_id,
       text
FROM edit_history
WHERE chat_id = $1
  AND message_id = $2
ORDER BY edit_id
`

func (q *Queries) ListEditHistoryByMessage(ctx context.Context, chatID int64, messageID int64) ([]EditHistory, error) {
	rows, err := q.db.Query(ctx, listEditHistoryByMessage, chatID, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EditHistory
	for rows.Next() {
		var i EditHistory
		if err := rows.Scan(
			&i.ChatID,
			&i.MessageID,
			&i.EditID,
			&i.Text,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMessageText = `-- name: UpdateMessageText :exec
UPDATE saved_msgs
SET text=$1,
    entities_json=$2,
    edit_date=$3
WHERE chat_id = $4
  AND message_id = $5
`

type UpdateMessageTextParams struct {
	Text         sql.NullString     `json:"text"`
	EntitiesJson []byte             `json:"entities_json"`
	EditDate     sql.Null[UnixTime] `json:"edit_date"`
	ChatID       int64              `json:"chat_id"`
	MessageID    int64              `json:"message_id"`
}

func (q *Queries) UpdateMessageText(ctx context.Context, arg UpdateMessageTextParams) error {
	_, err := q.db.Exec(ctx, updateMessageText,
		arg.Text,
		arg.EntitiesJson,
		arg.EditDate,
		arg.ChatID,
		arg.MessageID,
	)
	return err
}
