// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package q

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"time"

	"go.uber.org/zap"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.addGeminiMessageStmt, err = db.PrepareContext(ctx, addGeminiMessage); err != nil {
		return nil, fmt.Errorf("error preparing query AddGeminiMessage: %w", err)
	}
	if q.createNewGeminiSessionStmt, err = db.PrepareContext(ctx, createNewGeminiSession); err != nil {
		return nil, fmt.Errorf("error preparing query CreateNewGeminiSession: %w", err)
	}
	if q.delCocCharAttrStmt, err = db.PrepareContext(ctx, delCocCharAttr); err != nil {
		return nil, fmt.Errorf("error preparing query DelCocCharAttr: %w", err)
	}
	if q.getBiliInlineDataStmt, err = db.PrepareContext(ctx, getBiliInlineData); err != nil {
		return nil, fmt.Errorf("error preparing query GetBiliInlineData: %w", err)
	}
	if q.getCocCharAllAttrStmt, err = db.PrepareContext(ctx, getCocCharAllAttr); err != nil {
		return nil, fmt.Errorf("error preparing query GetCocCharAllAttr: %w", err)
	}
	if q.getCocCharAttrStmt, err = db.PrepareContext(ctx, getCocCharAttr); err != nil {
		return nil, fmt.Errorf("error preparing query GetCocCharAttr: %w", err)
	}
	if q.getNsfwPicByFileUidStmt, err = db.PrepareContext(ctx, getNsfwPicByFileUid); err != nil {
		return nil, fmt.Errorf("error preparing query GetNsfwPicByFileUid: %w", err)
	}
	if q.getPicRateDetailsByFileUidStmt, err = db.PrepareContext(ctx, getPicRateDetailsByFileUid); err != nil {
		return nil, fmt.Errorf("error preparing query GetPicRateDetailsByFileUid: %w", err)
	}
	if q.getPrprCacheStmt, err = db.PrepareContext(ctx, getPrprCache); err != nil {
		return nil, fmt.Errorf("error preparing query GetPrprCache: %w", err)
	}
	if q.getSessionByIdStmt, err = db.PrepareContext(ctx, getSessionById); err != nil {
		return nil, fmt.Errorf("error preparing query GetSessionById: %w", err)
	}
	if q.getSessionIdByMessageStmt, err = db.PrepareContext(ctx, getSessionIdByMessage); err != nil {
		return nil, fmt.Errorf("error preparing query GetSessionIdByMessage: %w", err)
	}
	if q.getYtDlpDbCacheStmt, err = db.PrepareContext(ctx, getYtDlpDbCache); err != nil {
		return nil, fmt.Errorf("error preparing query GetYtDlpDbCache: %w", err)
	}
	if q.incYtDlUploadCountStmt, err = db.PrepareContext(ctx, incYtDlUploadCount); err != nil {
		return nil, fmt.Errorf("error preparing query IncYtDlUploadCount: %w", err)
	}
	if q.insertBiliInlineDataStmt, err = db.PrepareContext(ctx, insertBiliInlineData); err != nil {
		return nil, fmt.Errorf("error preparing query InsertBiliInlineData: %w", err)
	}
	if q.setCocCharAttrStmt, err = db.PrepareContext(ctx, setCocCharAttr); err != nil {
		return nil, fmt.Errorf("error preparing query SetCocCharAttr: %w", err)
	}
	if q.setPrprCacheStmt, err = db.PrepareContext(ctx, setPrprCache); err != nil {
		return nil, fmt.Errorf("error preparing query SetPrprCache: %w", err)
	}
	if q.updateBiliInlineMsgIdStmt, err = db.PrepareContext(ctx, updateBiliInlineMsgId); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateBiliInlineMsgId: %w", err)
	}
	if q.updateChatStatDailyStmt, err = db.PrepareContext(ctx, updateChatStatDaily); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateChatStatDaily: %w", err)
	}
	if q.updateYtDlpCacheStmt, err = db.PrepareContext(ctx, updateYtDlpCache); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateYtDlpCache: %w", err)
	}
	if q.chatCfgByIdStmt, err = db.PrepareContext(ctx, chatCfgById); err != nil {
		return nil, fmt.Errorf("error preparing query chatCfgById: %w", err)
	}
	if q.chatIdByWebIdStmt, err = db.PrepareContext(ctx, chatIdByWebId); err != nil {
		return nil, fmt.Errorf("error preparing query chatIdByWebId: %w", err)
	}
	if q.createChatStatDailyStmt, err = db.PrepareContext(ctx, createChatStatDaily); err != nil {
		return nil, fmt.Errorf("error preparing query createChatStatDaily: %w", err)
	}
	if q.createNewChatCfgDefaultStmt, err = db.PrepareContext(ctx, createNewChatCfgDefault); err != nil {
		return nil, fmt.Errorf("error preparing query createNewChatCfgDefault: %w", err)
	}
	if q.createNewUserStmt, err = db.PrepareContext(ctx, createNewUser); err != nil {
		return nil, fmt.Errorf("error preparing query createNewUser: %w", err)
	}
	if q.getAllMsgInSessionReversedStmt, err = db.PrepareContext(ctx, getAllMsgInSessionReversed); err != nil {
		return nil, fmt.Errorf("error preparing query getAllMsgInSessionReversed: %w", err)
	}
	if q.getChatStatStmt, err = db.PrepareContext(ctx, getChatStat); err != nil {
		return nil, fmt.Errorf("error preparing query getChatStat: %w", err)
	}
	if q.getPicByRateAndRandKeyStmt, err = db.PrepareContext(ctx, getPicByRateAndRandKey); err != nil {
		return nil, fmt.Errorf("error preparing query getPicByRateAndRandKey: %w", err)
	}
	if q.getPicByRateFirstStmt, err = db.PrepareContext(ctx, getPicByRateFirst); err != nil {
		return nil, fmt.Errorf("error preparing query getPicByRateFirst: %w", err)
	}
	if q.getPicRateByUserIdStmt, err = db.PrepareContext(ctx, getPicRateByUserId); err != nil {
		return nil, fmt.Errorf("error preparing query getPicRateByUserId: %w", err)
	}
	if q.getPicRateCountsStmt, err = db.PrepareContext(ctx, getPicRateCounts); err != nil {
		return nil, fmt.Errorf("error preparing query getPicRateCounts: %w", err)
	}
	if q.getUserByIdStmt, err = db.PrepareContext(ctx, getUserById); err != nil {
		return nil, fmt.Errorf("error preparing query getUserById: %w", err)
	}
	if q.insertPicStmt, err = db.PrepareContext(ctx, insertPic); err != nil {
		return nil, fmt.Errorf("error preparing query insertPic: %w", err)
	}
	if q.ratePicStmt, err = db.PrepareContext(ctx, ratePic); err != nil {
		return nil, fmt.Errorf("error preparing query ratePic: %w", err)
	}
	if q.updateChatCfgStmt, err = db.PrepareContext(ctx, updateChatCfg); err != nil {
		return nil, fmt.Errorf("error preparing query updateChatCfg: %w", err)
	}
	if q.updatePicRateStmt, err = db.PrepareContext(ctx, updatePicRate); err != nil {
		return nil, fmt.Errorf("error preparing query updatePicRate: %w", err)
	}
	if q.updateUserBaseStmt, err = db.PrepareContext(ctx, updateUserBase); err != nil {
		return nil, fmt.Errorf("error preparing query updateUserBase: %w", err)
	}
	if q.updateUserProfilePhotoStmt, err = db.PrepareContext(ctx, updateUserProfilePhoto); err != nil {
		return nil, fmt.Errorf("error preparing query updateUserProfilePhoto: %w", err)
	}
	if q.updateUserTimeZoneStmt, err = db.PrepareContext(ctx, updateUserTimeZone); err != nil {
		return nil, fmt.Errorf("error preparing query updateUserTimeZone: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.addGeminiMessageStmt != nil {
		if cerr := q.addGeminiMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addGeminiMessageStmt: %w", cerr)
		}
	}
	if q.createNewGeminiSessionStmt != nil {
		if cerr := q.createNewGeminiSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createNewGeminiSessionStmt: %w", cerr)
		}
	}
	if q.delCocCharAttrStmt != nil {
		if cerr := q.delCocCharAttrStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing delCocCharAttrStmt: %w", cerr)
		}
	}
	if q.getBiliInlineDataStmt != nil {
		if cerr := q.getBiliInlineDataStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBiliInlineDataStmt: %w", cerr)
		}
	}
	if q.getCocCharAllAttrStmt != nil {
		if cerr := q.getCocCharAllAttrStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCocCharAllAttrStmt: %w", cerr)
		}
	}
	if q.getCocCharAttrStmt != nil {
		if cerr := q.getCocCharAttrStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCocCharAttrStmt: %w", cerr)
		}
	}
	if q.getNsfwPicByFileUidStmt != nil {
		if cerr := q.getNsfwPicByFileUidStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getNsfwPicByFileUidStmt: %w", cerr)
		}
	}
	if q.getPicRateDetailsByFileUidStmt != nil {
		if cerr := q.getPicRateDetailsByFileUidStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPicRateDetailsByFileUidStmt: %w", cerr)
		}
	}
	if q.getPrprCacheStmt != nil {
		if cerr := q.getPrprCacheStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPrprCacheStmt: %w", cerr)
		}
	}
	if q.getSessionByIdStmt != nil {
		if cerr := q.getSessionByIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSessionByIdStmt: %w", cerr)
		}
	}
	if q.getSessionIdByMessageStmt != nil {
		if cerr := q.getSessionIdByMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSessionIdByMessageStmt: %w", cerr)
		}
	}
	if q.getYtDlpDbCacheStmt != nil {
		if cerr := q.getYtDlpDbCacheStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getYtDlpDbCacheStmt: %w", cerr)
		}
	}
	if q.incYtDlUploadCountStmt != nil {
		if cerr := q.incYtDlUploadCountStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing incYtDlUploadCountStmt: %w", cerr)
		}
	}
	if q.insertBiliInlineDataStmt != nil {
		if cerr := q.insertBiliInlineDataStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertBiliInlineDataStmt: %w", cerr)
		}
	}
	if q.setCocCharAttrStmt != nil {
		if cerr := q.setCocCharAttrStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setCocCharAttrStmt: %w", cerr)
		}
	}
	if q.setPrprCacheStmt != nil {
		if cerr := q.setPrprCacheStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setPrprCacheStmt: %w", cerr)
		}
	}
	if q.updateBiliInlineMsgIdStmt != nil {
		if cerr := q.updateBiliInlineMsgIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateBiliInlineMsgIdStmt: %w", cerr)
		}
	}
	if q.updateChatStatDailyStmt != nil {
		if cerr := q.updateChatStatDailyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateChatStatDailyStmt: %w", cerr)
		}
	}
	if q.updateYtDlpCacheStmt != nil {
		if cerr := q.updateYtDlpCacheStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateYtDlpCacheStmt: %w", cerr)
		}
	}
	if q.chatCfgByIdStmt != nil {
		if cerr := q.chatCfgByIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing chatCfgByIdStmt: %w", cerr)
		}
	}
	if q.chatIdByWebIdStmt != nil {
		if cerr := q.chatIdByWebIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing chatIdByWebIdStmt: %w", cerr)
		}
	}
	if q.createChatStatDailyStmt != nil {
		if cerr := q.createChatStatDailyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createChatStatDailyStmt: %w", cerr)
		}
	}
	if q.createNewChatCfgDefaultStmt != nil {
		if cerr := q.createNewChatCfgDefaultStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createNewChatCfgDefaultStmt: %w", cerr)
		}
	}
	if q.createNewUserStmt != nil {
		if cerr := q.createNewUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createNewUserStmt: %w", cerr)
		}
	}
	if q.getAllMsgInSessionReversedStmt != nil {
		if cerr := q.getAllMsgInSessionReversedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllMsgInSessionReversedStmt: %w", cerr)
		}
	}
	if q.getChatStatStmt != nil {
		if cerr := q.getChatStatStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getChatStatStmt: %w", cerr)
		}
	}
	if q.getPicByRateAndRandKeyStmt != nil {
		if cerr := q.getPicByRateAndRandKeyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPicByRateAndRandKeyStmt: %w", cerr)
		}
	}
	if q.getPicByRateFirstStmt != nil {
		if cerr := q.getPicByRateFirstStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPicByRateFirstStmt: %w", cerr)
		}
	}
	if q.getPicRateByUserIdStmt != nil {
		if cerr := q.getPicRateByUserIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPicRateByUserIdStmt: %w", cerr)
		}
	}
	if q.getPicRateCountsStmt != nil {
		if cerr := q.getPicRateCountsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPicRateCountsStmt: %w", cerr)
		}
	}
	if q.getUserByIdStmt != nil {
		if cerr := q.getUserByIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByIdStmt: %w", cerr)
		}
	}
	if q.insertPicStmt != nil {
		if cerr := q.insertPicStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertPicStmt: %w", cerr)
		}
	}
	if q.ratePicStmt != nil {
		if cerr := q.ratePicStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing ratePicStmt: %w", cerr)
		}
	}
	if q.updateChatCfgStmt != nil {
		if cerr := q.updateChatCfgStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateChatCfgStmt: %w", cerr)
		}
	}
	if q.updatePicRateStmt != nil {
		if cerr := q.updatePicRateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updatePicRateStmt: %w", cerr)
		}
	}
	if q.updateUserBaseStmt != nil {
		if cerr := q.updateUserBaseStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserBaseStmt: %w", cerr)
		}
	}
	if q.updateUserProfilePhotoStmt != nil {
		if cerr := q.updateUserProfilePhotoStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserProfilePhotoStmt: %w", cerr)
		}
	}
	if q.updateUserTimeZoneStmt != nil {
		if cerr := q.updateUserTimeZoneStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserTimeZoneStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                             DBTX
	logger                         *zap.Logger
	SlowQueryThreshold             time.Duration
	txID                           string
	tx                             *sql.Tx
	addGeminiMessageStmt           *sql.Stmt
	createNewGeminiSessionStmt     *sql.Stmt
	delCocCharAttrStmt             *sql.Stmt
	getBiliInlineDataStmt          *sql.Stmt
	getCocCharAllAttrStmt          *sql.Stmt
	getCocCharAttrStmt             *sql.Stmt
	getNsfwPicByFileUidStmt        *sql.Stmt
	getPicRateDetailsByFileUidStmt *sql.Stmt
	getPrprCacheStmt               *sql.Stmt
	getSessionByIdStmt             *sql.Stmt
	getSessionIdByMessageStmt      *sql.Stmt
	getYtDlpDbCacheStmt            *sql.Stmt
	incYtDlUploadCountStmt         *sql.Stmt
	insertBiliInlineDataStmt       *sql.Stmt
	setCocCharAttrStmt             *sql.Stmt
	setPrprCacheStmt               *sql.Stmt
	updateBiliInlineMsgIdStmt      *sql.Stmt
	updateChatStatDailyStmt        *sql.Stmt
	updateYtDlpCacheStmt           *sql.Stmt
	chatCfgByIdStmt                *sql.Stmt
	chatIdByWebIdStmt              *sql.Stmt
	createChatStatDailyStmt        *sql.Stmt
	createNewChatCfgDefaultStmt    *sql.Stmt
	createNewUserStmt              *sql.Stmt
	getAllMsgInSessionReversedStmt *sql.Stmt
	getChatStatStmt                *sql.Stmt
	getPicByRateAndRandKeyStmt     *sql.Stmt
	getPicByRateFirstStmt          *sql.Stmt
	getPicRateByUserIdStmt         *sql.Stmt
	getPicRateCountsStmt           *sql.Stmt
	getUserByIdStmt                *sql.Stmt
	insertPicStmt                  *sql.Stmt
	ratePicStmt                    *sql.Stmt
	updateChatCfgStmt              *sql.Stmt
	updatePicRateStmt              *sql.Stmt
	updateUserBaseStmt             *sql.Stmt
	updateUserProfilePhotoStmt     *sql.Stmt
	updateUserTimeZoneStmt         *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                             tx,
		logger:                         q.logger,
		SlowQueryThreshold:             q.SlowQueryThreshold,
		txID:                           fmt.Sprintf("%p", tx),
		tx:                             tx,
		addGeminiMessageStmt:           q.addGeminiMessageStmt,
		createNewGeminiSessionStmt:     q.createNewGeminiSessionStmt,
		delCocCharAttrStmt:             q.delCocCharAttrStmt,
		getBiliInlineDataStmt:          q.getBiliInlineDataStmt,
		getCocCharAllAttrStmt:          q.getCocCharAllAttrStmt,
		getCocCharAttrStmt:             q.getCocCharAttrStmt,
		getNsfwPicByFileUidStmt:        q.getNsfwPicByFileUidStmt,
		getPicRateDetailsByFileUidStmt: q.getPicRateDetailsByFileUidStmt,
		getPrprCacheStmt:               q.getPrprCacheStmt,
		getSessionByIdStmt:             q.getSessionByIdStmt,
		getSessionIdByMessageStmt:      q.getSessionIdByMessageStmt,
		getYtDlpDbCacheStmt:            q.getYtDlpDbCacheStmt,
		incYtDlUploadCountStmt:         q.incYtDlUploadCountStmt,
		insertBiliInlineDataStmt:       q.insertBiliInlineDataStmt,
		setCocCharAttrStmt:             q.setCocCharAttrStmt,
		setPrprCacheStmt:               q.setPrprCacheStmt,
		updateBiliInlineMsgIdStmt:      q.updateBiliInlineMsgIdStmt,
		updateChatStatDailyStmt:        q.updateChatStatDailyStmt,
		updateYtDlpCacheStmt:           q.updateYtDlpCacheStmt,
		chatCfgByIdStmt:                q.chatCfgByIdStmt,
		chatIdByWebIdStmt:              q.chatIdByWebIdStmt,
		createChatStatDailyStmt:        q.createChatStatDailyStmt,
		createNewChatCfgDefaultStmt:    q.createNewChatCfgDefaultStmt,
		createNewUserStmt:              q.createNewUserStmt,
		getAllMsgInSessionReversedStmt: q.getAllMsgInSessionReversedStmt,
		getChatStatStmt:                q.getChatStatStmt,
		getPicByRateAndRandKeyStmt:     q.getPicByRateAndRandKeyStmt,
		getPicByRateFirstStmt:          q.getPicByRateFirstStmt,
		getPicRateByUserIdStmt:         q.getPicRateByUserIdStmt,
		getPicRateCountsStmt:           q.getPicRateCountsStmt,
		getUserByIdStmt:                q.getUserByIdStmt,
		insertPicStmt:                  q.insertPicStmt,
		ratePicStmt:                    q.ratePicStmt,
		updateChatCfgStmt:              q.updateChatCfgStmt,
		updatePicRateStmt:              q.updatePicRateStmt,
		updateUserBaseStmt:             q.updateUserBaseStmt,
		updateUserProfilePhotoStmt:     q.updateUserProfilePhotoStmt,
		updateUserTimeZoneStmt:         q.updateUserTimeZoneStmt,
	}
}

func (q *Queries) logQuery(query string, params []zap.Field, err error, start time.Time) {
	if q.logger == nil {
		return
	}

	duration := time.Since(start)
	fields := make([]zap.Field, 0, len(params)+4)
	fields = append(fields,
		zap.Time("ts", start),
		zap.String("sql", query),
	)
	if q.txID != "" {
		fields = append(fields, zap.String("txID", q.txID))
	}
	fields = append(fields, params...)
	fields = append(fields, zap.Duration("duration", duration))
	if err != nil {
		fields = append(fields, zap.Error(err))
	}

	if q.SlowQueryThreshold > 0 && duration > q.SlowQueryThreshold {
		q.logger.Warn("slow query", fields...)
		return
	}
	if err != nil && !errors.Is(err, sql.ErrNoRows) {
		q.logger.Error("query failed", fields...)
		return
	}
	q.logger.Info("query", fields...)
}

func zapNullString(key string, v sql.NullString) zap.Field {
	if v.Valid {
		return zap.String(key, v.String)
	}
	return zap.String(key, "<nil>")
}

func zapNullBool(key string, v sql.NullBool) zap.Field {
	if v.Valid {
		return zap.Bool(key, v.Bool)
	}
	return zap.String(key, "<nil>")
}

func zapNullInt32(key string, v sql.NullInt32) zap.Field {
	if v.Valid {
		return zap.Int32(key, v.Int32)
	}
	return zap.String(key, "<nil>")
}

func zapNullInt64(key string, v sql.NullInt64) zap.Field {
	if v.Valid {
		return zap.Int64(key, v.Int64)
	}
	return zap.String(key, "<nil>")
}

func zapNullFloat64(key string, v sql.NullFloat64) zap.Field {
	if v.Valid {
		return zap.Float64(key, v.Float64)
	}
	return zap.String(key, "<nil>")
}

func zapNullTime(key string, v sql.NullTime) zap.Field {
	if v.Valid {
		return zap.Time(key, v.Time)
	}
	return zap.String(key, "<nil>")
}
