// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package q

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"time"

	"go.uber.org/zap"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.addGeminiMessageStmt, err = db.PrepareContext(ctx, addGeminiMessage); err != nil {
		return nil, fmt.Errorf("error preparing query AddGeminiMessage: %w", err)
	}
	if q.createChatCfgStmt, err = db.PrepareContext(ctx, createChatCfg); err != nil {
		return nil, fmt.Errorf("error preparing query CreateChatCfg: %w", err)
	}
	if q.createNewGeminiSessionStmt, err = db.PrepareContext(ctx, createNewGeminiSession); err != nil {
		return nil, fmt.Errorf("error preparing query CreateNewGeminiSession: %w", err)
	}
	if q.delCocCharAttrStmt, err = db.PrepareContext(ctx, delCocCharAttr); err != nil {
		return nil, fmt.Errorf("error preparing query DelCocCharAttr: %w", err)
	}
	if q.getBiliInlineDataStmt, err = db.PrepareContext(ctx, getBiliInlineData); err != nil {
		return nil, fmt.Errorf("error preparing query GetBiliInlineData: %w", err)
	}
	if q.getCocCharAllAttrStmt, err = db.PrepareContext(ctx, getCocCharAllAttr); err != nil {
		return nil, fmt.Errorf("error preparing query GetCocCharAllAttr: %w", err)
	}
	if q.getCocCharAttrStmt, err = db.PrepareContext(ctx, getCocCharAttr); err != nil {
		return nil, fmt.Errorf("error preparing query GetCocCharAttr: %w", err)
	}
	if q.getNsfwPicByFileUidStmt, err = db.PrepareContext(ctx, getNsfwPicByFileUid); err != nil {
		return nil, fmt.Errorf("error preparing query GetNsfwPicByFileUid: %w", err)
	}
	if q.getPrprCacheStmt, err = db.PrepareContext(ctx, getPrprCache); err != nil {
		return nil, fmt.Errorf("error preparing query GetPrprCache: %w", err)
	}
	if q.getSessionByIdStmt, err = db.PrepareContext(ctx, getSessionById); err != nil {
		return nil, fmt.Errorf("error preparing query GetSessionById: %w", err)
	}
	if q.getSessionIdByMessageStmt, err = db.PrepareContext(ctx, getSessionIdByMessage); err != nil {
		return nil, fmt.Errorf("error preparing query GetSessionIdByMessage: %w", err)
	}
	if q.getYtDlpDbCacheStmt, err = db.PrepareContext(ctx, getYtDlpDbCache); err != nil {
		return nil, fmt.Errorf("error preparing query GetYtDlpDbCache: %w", err)
	}
	if q.incYtDlUploadCountStmt, err = db.PrepareContext(ctx, incYtDlUploadCount); err != nil {
		return nil, fmt.Errorf("error preparing query IncYtDlUploadCount: %w", err)
	}
	if q.insertBiliInlineDataStmt, err = db.PrepareContext(ctx, insertBiliInlineData); err != nil {
		return nil, fmt.Errorf("error preparing query InsertBiliInlineData: %w", err)
	}
	if q.listNsfwPicUserRatesByFileUidStmt, err = db.PrepareContext(ctx, listNsfwPicUserRatesByFileUid); err != nil {
		return nil, fmt.Errorf("error preparing query ListNsfwPicUserRatesByFileUid: %w", err)
	}
	if q.setCocCharAttrStmt, err = db.PrepareContext(ctx, setCocCharAttr); err != nil {
		return nil, fmt.Errorf("error preparing query SetCocCharAttr: %w", err)
	}
	if q.setPrprCacheStmt, err = db.PrepareContext(ctx, setPrprCache); err != nil {
		return nil, fmt.Errorf("error preparing query SetPrprCache: %w", err)
	}
	if q.updateBiliInlineMsgIdStmt, err = db.PrepareContext(ctx, updateBiliInlineMsgId); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateBiliInlineMsgId: %w", err)
	}
	if q.updateChatStatDailyStmt, err = db.PrepareContext(ctx, updateChatStatDaily); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateChatStatDaily: %w", err)
	}
	if q.updateYtDlpCacheStmt, err = db.PrepareContext(ctx, updateYtDlpCache); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateYtDlpCache: %w", err)
	}
	if q.createChatStatDailyStmt, err = db.PrepareContext(ctx, createChatStatDaily); err != nil {
		return nil, fmt.Errorf("error preparing query createChatStatDaily: %w", err)
	}
	if q.createNewUserStmt, err = db.PrepareContext(ctx, createNewUser); err != nil {
		return nil, fmt.Errorf("error preparing query createNewUser: %w", err)
	}
	if q.createNsfwPicUserRateStmt, err = db.PrepareContext(ctx, createNsfwPicUserRate); err != nil {
		return nil, fmt.Errorf("error preparing query createNsfwPicUserRate: %w", err)
	}
	if q.createOrUpdateNsfwPicStmt, err = db.PrepareContext(ctx, createOrUpdateNsfwPic); err != nil {
		return nil, fmt.Errorf("error preparing query createOrUpdateNsfwPic: %w", err)
	}
	if q.getAllMsgInSessionReversedStmt, err = db.PrepareContext(ctx, getAllMsgInSessionReversed); err != nil {
		return nil, fmt.Errorf("error preparing query getAllMsgInSessionReversed: %w", err)
	}
	if q.getChatCfgByIdStmt, err = db.PrepareContext(ctx, getChatCfgById); err != nil {
		return nil, fmt.Errorf("error preparing query getChatCfgById: %w", err)
	}
	if q.getChatIdByWebIdStmt, err = db.PrepareContext(ctx, getChatIdByWebId); err != nil {
		return nil, fmt.Errorf("error preparing query getChatIdByWebId: %w", err)
	}
	if q.getChatStatStmt, err = db.PrepareContext(ctx, getChatStat); err != nil {
		return nil, fmt.Errorf("error preparing query getChatStat: %w", err)
	}
	if q.getNsfwPicByRateAndRandKeyStmt, err = db.PrepareContext(ctx, getNsfwPicByRateAndRandKey); err != nil {
		return nil, fmt.Errorf("error preparing query getNsfwPicByRateAndRandKey: %w", err)
	}
	if q.getNsfwPicByRateFirstStmt, err = db.PrepareContext(ctx, getNsfwPicByRateFirst); err != nil {
		return nil, fmt.Errorf("error preparing query getNsfwPicByRateFirst: %w", err)
	}
	if q.getNsfwPicRateByUserIdStmt, err = db.PrepareContext(ctx, getNsfwPicRateByUserId); err != nil {
		return nil, fmt.Errorf("error preparing query getNsfwPicRateByUserId: %w", err)
	}
	if q.getUserByIdStmt, err = db.PrepareContext(ctx, getUserById); err != nil {
		return nil, fmt.Errorf("error preparing query getUserById: %w", err)
	}
	if q.listNsfwPicRateCounterStmt, err = db.PrepareContext(ctx, listNsfwPicRateCounter); err != nil {
		return nil, fmt.Errorf("error preparing query listNsfwPicRateCounter: %w", err)
	}
	if q.updateChatCfgStmt, err = db.PrepareContext(ctx, updateChatCfg); err != nil {
		return nil, fmt.Errorf("error preparing query updateChatCfg: %w", err)
	}
	if q.updateNsfwPicUserRateStmt, err = db.PrepareContext(ctx, updateNsfwPicUserRate); err != nil {
		return nil, fmt.Errorf("error preparing query updateNsfwPicUserRate: %w", err)
	}
	if q.updateUserBaseStmt, err = db.PrepareContext(ctx, updateUserBase); err != nil {
		return nil, fmt.Errorf("error preparing query updateUserBase: %w", err)
	}
	if q.updateUserProfilePhotoStmt, err = db.PrepareContext(ctx, updateUserProfilePhoto); err != nil {
		return nil, fmt.Errorf("error preparing query updateUserProfilePhoto: %w", err)
	}
	if q.updateUserTimeZoneStmt, err = db.PrepareContext(ctx, updateUserTimeZone); err != nil {
		return nil, fmt.Errorf("error preparing query updateUserTimeZone: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.addGeminiMessageStmt != nil {
		if cerr := q.addGeminiMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addGeminiMessageStmt: %w", cerr)
		}
	}
	if q.createChatCfgStmt != nil {
		if cerr := q.createChatCfgStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createChatCfgStmt: %w", cerr)
		}
	}
	if q.createNewGeminiSessionStmt != nil {
		if cerr := q.createNewGeminiSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createNewGeminiSessionStmt: %w", cerr)
		}
	}
	if q.delCocCharAttrStmt != nil {
		if cerr := q.delCocCharAttrStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing delCocCharAttrStmt: %w", cerr)
		}
	}
	if q.getBiliInlineDataStmt != nil {
		if cerr := q.getBiliInlineDataStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBiliInlineDataStmt: %w", cerr)
		}
	}
	if q.getCocCharAllAttrStmt != nil {
		if cerr := q.getCocCharAllAttrStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCocCharAllAttrStmt: %w", cerr)
		}
	}
	if q.getCocCharAttrStmt != nil {
		if cerr := q.getCocCharAttrStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCocCharAttrStmt: %w", cerr)
		}
	}
	if q.getNsfwPicByFileUidStmt != nil {
		if cerr := q.getNsfwPicByFileUidStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getNsfwPicByFileUidStmt: %w", cerr)
		}
	}
	if q.getPrprCacheStmt != nil {
		if cerr := q.getPrprCacheStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPrprCacheStmt: %w", cerr)
		}
	}
	if q.getSessionByIdStmt != nil {
		if cerr := q.getSessionByIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSessionByIdStmt: %w", cerr)
		}
	}
	if q.getSessionIdByMessageStmt != nil {
		if cerr := q.getSessionIdByMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSessionIdByMessageStmt: %w", cerr)
		}
	}
	if q.getYtDlpDbCacheStmt != nil {
		if cerr := q.getYtDlpDbCacheStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getYtDlpDbCacheStmt: %w", cerr)
		}
	}
	if q.incYtDlUploadCountStmt != nil {
		if cerr := q.incYtDlUploadCountStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing incYtDlUploadCountStmt: %w", cerr)
		}
	}
	if q.insertBiliInlineDataStmt != nil {
		if cerr := q.insertBiliInlineDataStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertBiliInlineDataStmt: %w", cerr)
		}
	}
	if q.listNsfwPicUserRatesByFileUidStmt != nil {
		if cerr := q.listNsfwPicUserRatesByFileUidStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listNsfwPicUserRatesByFileUidStmt: %w", cerr)
		}
	}
	if q.setCocCharAttrStmt != nil {
		if cerr := q.setCocCharAttrStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setCocCharAttrStmt: %w", cerr)
		}
	}
	if q.setPrprCacheStmt != nil {
		if cerr := q.setPrprCacheStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setPrprCacheStmt: %w", cerr)
		}
	}
	if q.updateBiliInlineMsgIdStmt != nil {
		if cerr := q.updateBiliInlineMsgIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateBiliInlineMsgIdStmt: %w", cerr)
		}
	}
	if q.updateChatStatDailyStmt != nil {
		if cerr := q.updateChatStatDailyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateChatStatDailyStmt: %w", cerr)
		}
	}
	if q.updateYtDlpCacheStmt != nil {
		if cerr := q.updateYtDlpCacheStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateYtDlpCacheStmt: %w", cerr)
		}
	}
	if q.createChatStatDailyStmt != nil {
		if cerr := q.createChatStatDailyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createChatStatDailyStmt: %w", cerr)
		}
	}
	if q.createNewUserStmt != nil {
		if cerr := q.createNewUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createNewUserStmt: %w", cerr)
		}
	}
	if q.createNsfwPicUserRateStmt != nil {
		if cerr := q.createNsfwPicUserRateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createNsfwPicUserRateStmt: %w", cerr)
		}
	}
	if q.createOrUpdateNsfwPicStmt != nil {
		if cerr := q.createOrUpdateNsfwPicStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createOrUpdateNsfwPicStmt: %w", cerr)
		}
	}
	if q.getAllMsgInSessionReversedStmt != nil {
		if cerr := q.getAllMsgInSessionReversedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllMsgInSessionReversedStmt: %w", cerr)
		}
	}
	if q.getChatCfgByIdStmt != nil {
		if cerr := q.getChatCfgByIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getChatCfgByIdStmt: %w", cerr)
		}
	}
	if q.getChatIdByWebIdStmt != nil {
		if cerr := q.getChatIdByWebIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getChatIdByWebIdStmt: %w", cerr)
		}
	}
	if q.getChatStatStmt != nil {
		if cerr := q.getChatStatStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getChatStatStmt: %w", cerr)
		}
	}
	if q.getNsfwPicByRateAndRandKeyStmt != nil {
		if cerr := q.getNsfwPicByRateAndRandKeyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getNsfwPicByRateAndRandKeyStmt: %w", cerr)
		}
	}
	if q.getNsfwPicByRateFirstStmt != nil {
		if cerr := q.getNsfwPicByRateFirstStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getNsfwPicByRateFirstStmt: %w", cerr)
		}
	}
	if q.getNsfwPicRateByUserIdStmt != nil {
		if cerr := q.getNsfwPicRateByUserIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getNsfwPicRateByUserIdStmt: %w", cerr)
		}
	}
	if q.getUserByIdStmt != nil {
		if cerr := q.getUserByIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByIdStmt: %w", cerr)
		}
	}
	if q.listNsfwPicRateCounterStmt != nil {
		if cerr := q.listNsfwPicRateCounterStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listNsfwPicRateCounterStmt: %w", cerr)
		}
	}
	if q.updateChatCfgStmt != nil {
		if cerr := q.updateChatCfgStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateChatCfgStmt: %w", cerr)
		}
	}
	if q.updateNsfwPicUserRateStmt != nil {
		if cerr := q.updateNsfwPicUserRateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateNsfwPicUserRateStmt: %w", cerr)
		}
	}
	if q.updateUserBaseStmt != nil {
		if cerr := q.updateUserBaseStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserBaseStmt: %w", cerr)
		}
	}
	if q.updateUserProfilePhotoStmt != nil {
		if cerr := q.updateUserProfilePhotoStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserProfilePhotoStmt: %w", cerr)
		}
	}
	if q.updateUserTimeZoneStmt != nil {
		if cerr := q.updateUserTimeZoneStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserTimeZoneStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                DBTX
	logger                            *zap.Logger
	SlowQueryThreshold                time.Duration
	txID                              string
	tx                                *sql.Tx
	addGeminiMessageStmt              *sql.Stmt
	createChatCfgStmt                 *sql.Stmt
	createNewGeminiSessionStmt        *sql.Stmt
	delCocCharAttrStmt                *sql.Stmt
	getBiliInlineDataStmt             *sql.Stmt
	getCocCharAllAttrStmt             *sql.Stmt
	getCocCharAttrStmt                *sql.Stmt
	getNsfwPicByFileUidStmt           *sql.Stmt
	getPrprCacheStmt                  *sql.Stmt
	getSessionByIdStmt                *sql.Stmt
	getSessionIdByMessageStmt         *sql.Stmt
	getYtDlpDbCacheStmt               *sql.Stmt
	incYtDlUploadCountStmt            *sql.Stmt
	insertBiliInlineDataStmt          *sql.Stmt
	listNsfwPicUserRatesByFileUidStmt *sql.Stmt
	setCocCharAttrStmt                *sql.Stmt
	setPrprCacheStmt                  *sql.Stmt
	updateBiliInlineMsgIdStmt         *sql.Stmt
	updateChatStatDailyStmt           *sql.Stmt
	updateYtDlpCacheStmt              *sql.Stmt
	createChatStatDailyStmt           *sql.Stmt
	createNewUserStmt                 *sql.Stmt
	createNsfwPicUserRateStmt         *sql.Stmt
	createOrUpdateNsfwPicStmt         *sql.Stmt
	getAllMsgInSessionReversedStmt    *sql.Stmt
	getChatCfgByIdStmt                *sql.Stmt
	getChatIdByWebIdStmt              *sql.Stmt
	getChatStatStmt                   *sql.Stmt
	getNsfwPicByRateAndRandKeyStmt    *sql.Stmt
	getNsfwPicByRateFirstStmt         *sql.Stmt
	getNsfwPicRateByUserIdStmt        *sql.Stmt
	getUserByIdStmt                   *sql.Stmt
	listNsfwPicRateCounterStmt        *sql.Stmt
	updateChatCfgStmt                 *sql.Stmt
	updateNsfwPicUserRateStmt         *sql.Stmt
	updateUserBaseStmt                *sql.Stmt
	updateUserProfilePhotoStmt        *sql.Stmt
	updateUserTimeZoneStmt            *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                tx,
		logger:                            q.logger,
		SlowQueryThreshold:                q.SlowQueryThreshold,
		txID:                              fmt.Sprintf("%p", tx),
		tx:                                tx,
		addGeminiMessageStmt:              q.addGeminiMessageStmt,
		createChatCfgStmt:                 q.createChatCfgStmt,
		createNewGeminiSessionStmt:        q.createNewGeminiSessionStmt,
		delCocCharAttrStmt:                q.delCocCharAttrStmt,
		getBiliInlineDataStmt:             q.getBiliInlineDataStmt,
		getCocCharAllAttrStmt:             q.getCocCharAllAttrStmt,
		getCocCharAttrStmt:                q.getCocCharAttrStmt,
		getNsfwPicByFileUidStmt:           q.getNsfwPicByFileUidStmt,
		getPrprCacheStmt:                  q.getPrprCacheStmt,
		getSessionByIdStmt:                q.getSessionByIdStmt,
		getSessionIdByMessageStmt:         q.getSessionIdByMessageStmt,
		getYtDlpDbCacheStmt:               q.getYtDlpDbCacheStmt,
		incYtDlUploadCountStmt:            q.incYtDlUploadCountStmt,
		insertBiliInlineDataStmt:          q.insertBiliInlineDataStmt,
		listNsfwPicUserRatesByFileUidStmt: q.listNsfwPicUserRatesByFileUidStmt,
		setCocCharAttrStmt:                q.setCocCharAttrStmt,
		setPrprCacheStmt:                  q.setPrprCacheStmt,
		updateBiliInlineMsgIdStmt:         q.updateBiliInlineMsgIdStmt,
		updateChatStatDailyStmt:           q.updateChatStatDailyStmt,
		updateYtDlpCacheStmt:              q.updateYtDlpCacheStmt,
		createChatStatDailyStmt:           q.createChatStatDailyStmt,
		createNewUserStmt:                 q.createNewUserStmt,
		createNsfwPicUserRateStmt:         q.createNsfwPicUserRateStmt,
		createOrUpdateNsfwPicStmt:         q.createOrUpdateNsfwPicStmt,
		getAllMsgInSessionReversedStmt:    q.getAllMsgInSessionReversedStmt,
		getChatCfgByIdStmt:                q.getChatCfgByIdStmt,
		getChatIdByWebIdStmt:              q.getChatIdByWebIdStmt,
		getChatStatStmt:                   q.getChatStatStmt,
		getNsfwPicByRateAndRandKeyStmt:    q.getNsfwPicByRateAndRandKeyStmt,
		getNsfwPicByRateFirstStmt:         q.getNsfwPicByRateFirstStmt,
		getNsfwPicRateByUserIdStmt:        q.getNsfwPicRateByUserIdStmt,
		getUserByIdStmt:                   q.getUserByIdStmt,
		listNsfwPicRateCounterStmt:        q.listNsfwPicRateCounterStmt,
		updateChatCfgStmt:                 q.updateChatCfgStmt,
		updateNsfwPicUserRateStmt:         q.updateNsfwPicUserRateStmt,
		updateUserBaseStmt:                q.updateUserBaseStmt,
		updateUserProfilePhotoStmt:        q.updateUserProfilePhotoStmt,
		updateUserTimeZoneStmt:            q.updateUserTimeZoneStmt,
	}
}

func (q *Queries) logQuery(query string, params []zap.Field, err error, start time.Time) {
	if q.logger == nil {
		return
	}

	duration := time.Since(start)
	fields := make([]zap.Field, 0, len(params)+4)
	fields = append(fields,
		zap.Time("ts", start),
		zap.String("sql", query),
	)
	if q.txID != "" {
		fields = append(fields, zap.String("txID", q.txID))
	}
	fields = append(fields, params...)
	fields = append(fields, zap.Duration("duration", duration))
	if err != nil {
		fields = append(fields, zap.Error(err))
	}

	if q.SlowQueryThreshold > 0 && duration > q.SlowQueryThreshold {
		q.logger.Warn("slow query", fields...)
		return
	}
	if err != nil && !errors.Is(err, sql.ErrNoRows) {
		q.logger.Error("query failed", fields...)
		return
	}
	q.logger.Info("query", fields...)
}

func zapNullString(key string, v sql.NullString) zap.Field {
	if v.Valid {
		return zap.String(key, v.String)
	}
	return zap.Any(key, nil)
}

func zapNullBool(key string, v sql.NullBool) zap.Field {
	if v.Valid {
		return zap.Bool(key, v.Bool)
	}
	return zap.Any(key, nil)
}

func zapNullInt32(key string, v sql.NullInt32) zap.Field {
	if v.Valid {
		return zap.Int32(key, v.Int32)
	}
	return zap.Any(key, nil)
}

func zapNullInt64(key string, v sql.NullInt64) zap.Field {
	if v.Valid {
		return zap.Int64(key, v.Int64)
	}
	return zap.Any(key, nil)
}

func zapNullFloat64(key string, v sql.NullFloat64) zap.Field {
	if v.Valid {
		return zap.Float64(key, v.Float64)
	}
	return zap.Any(key, nil)
}

func zapNullTime(key string, v sql.NullTime) zap.Field {
	if v.Valid {
		return zap.Time(key, v.Time)
	}
	return zap.Any(key, nil)
}

type zapObj interface {
	ZapObject(name string) zap.Field
}

func zapNullOf[T zapObj](name string, optObj sql.Null[T]) zap.Field {
	if optObj.Valid {
		return optObj.V.ZapObject(name)
	}
	return zap.Any(name, nil)
}
