// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package q

import (
	"database/sql"
)

type BiliInlineResult struct {
	Uid    int64  `json:"uid"`
	Text   string `json:"text"`
	ChatID int64  `json:"chat_id"`
	MsgID  int64  `json:"msg_id"`
}

type CharacterAttr struct {
	UserID    int64  `json:"user_id"`
	AttrName  string `json:"attr_name"`
	AttrValue string `json:"attr_value"`
}

type ChatAttr struct {
	ID        int64          `json:"id"`
	Type      string         `json:"type"`
	Title     sql.NullString `json:"title"`
	Username  sql.NullString `json:"username"`
	FirstName sql.NullString `json:"first_name"`
	LastName  sql.NullString `json:"last_name"`
	IsForum   bool           `json:"is_forum"`
}

type ChatStatDaily struct {
	ChatID             int64          `json:"chat_id"`
	StatDate           int64          `json:"stat_date"`
	MessageCount       int64          `json:"message_count"`
	PhotoCount         int64          `json:"photo_count"`
	VideoCount         int64          `json:"video_count"`
	StickerCount       int64          `json:"sticker_count"`
	ForwardCount       int64          `json:"forward_count"`
	MarsCount          int64          `json:"mars_count"`
	MaxMarsCount       int64          `json:"max_mars_count"`
	RacyCount          int64          `json:"racy_count"`
	AdultCount         int64          `json:"adult_count"`
	DownloadVideoCount int64          `json:"download_video_count"`
	DownloadAudioCount int64          `json:"download_audio_count"`
	DioAddUserCount    int64          `json:"dio_add_user_count"`
	DioBanUserCount    int64          `json:"dio_ban_user_count"`
	UserMsgStat        UserMsgStatMap `json:"user_msg_stat"`
	MsgCountByTime     TenMinuteStats `json:"msg_count_by_time"`
	MsgIDAtTimeStart   TenMinuteStats `json:"msg_id_at_time_start"`
}

type ChatTopic struct {
	ChatID   int64  `json:"chat_id"`
	ThreadID int64  `json:"thread_id"`
	Name     string `json:"name"`
}

type GeminiContent struct {
	SessionID        int64          `json:"session_id"`
	ChatID           int64          `json:"chat_id"`
	MsgID            int64          `json:"msg_id"`
	Role             string         `json:"role"`
	SentTime         UnixTime       `json:"sent_time"`
	Username         string         `json:"username"`
	MsgType          string         `json:"msg_type"`
	ReplyToMsgID     sql.NullInt64  `json:"reply_to_msg_id"`
	Text             sql.NullString `json:"text"`
	Blob             []byte         `json:"blob"`
	MimeType         sql.NullString `json:"mime_type"`
	QuotePart        sql.NullString `json:"quote_part"`
	ThoughtSignature sql.NullString `json:"thought_signature"`
	AtableUsername   sql.NullString `json:"atable_username"`
	UserID           int64          `json:"user_id"`
}

type GeminiSession struct {
	ID                int64  `json:"id"`
	ChatID            int64  `json:"chat_id"`
	ChatName          string `json:"chat_name"`
	ChatType          string `json:"chat_type"`
	Frozen            bool   `json:"frozen"`
	TotalInputTokens  int64  `json:"total_input_tokens"`
	TotalOutputTokens int64  `json:"total_output_tokens"`
}

type GeminiSystemPrompt struct {
	ChatID   int64  `json:"chat_id"`
	ThreadID int64  `json:"thread_id"`
	Prompt   string `json:"prompt"`
}

type PicRateCounter struct {
	Rate  int64 `json:"rate"`
	Count int64 `json:"count"`
}

type PrprCach struct {
	ProfilePhotoUid string `json:"profile_photo_uid"`
	PrprFileID      string `json:"prpr_file_id"`
}

type SavedPic struct {
	FileUid       string `json:"file_uid"`
	FileID        string `json:"file_id"`
	BotRate       int64  `json:"bot_rate"`
	RandKey       int64  `json:"rand_key"`
	UserRate      int64  `json:"user_rate"`
	UserRatingSum int64  `json:"user_rating_sum"`
	RateUserCount int64  `json:"rate_user_count"`
}

type SavedPicsRating struct {
	FileUid string `json:"file_uid"`
	UserID  int64  `json:"user_id"`
	Rating  int64  `json:"rating"`
}

type User struct {
	ID              int64          `json:"id"`
	UpdatedAt       UnixTime       `json:"updated_at"`
	UserID          int64          `json:"user_id"`
	FirstName       string         `json:"first_name"`
	LastName        sql.NullString `json:"last_name"`
	Username        sql.NullString `json:"username"`
	ProfileUpdateAt UnixTime       `json:"profile_update_at"`
	ProfilePhoto    sql.NullString `json:"profile_photo"`
	Timezone        int64          `json:"timezone"`
}

type YtDlResult struct {
	Url         string `json:"url"`
	AudioOnly   bool   `json:"audio_only"`
	Resolution  int64  `json:"resolution"`
	FileID      string `json:"file_id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	Uploader    string `json:"uploader"`
	UploadCount int64  `json:"upload_count"`
}

type chatCfg struct {
	ID             int64         `json:"id"`
	WebID          sql.NullInt64 `json:"web_id"`
	AutoCvtBili    bool          `json:"auto_cvt_bili"`
	AutoOcr        bool          `json:"auto_ocr"`
	AutoCalculate  bool          `json:"auto_calculate"`
	AutoExchange   bool          `json:"auto_exchange"`
	AutoCheckAdult bool          `json:"auto_check_adult"`
	SaveMessages   bool          `json:"save_messages"`
	EnableCoc      bool          `json:"enable_coc"`
	RespNsfwMsg    bool          `json:"resp_nsfw_msg"`
	Timezone       int64         `json:"timezone"`
}
