// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package q

import (
	"database/sql"
)

type BiliInlineResult struct {
	Uid    int64
	Text   string
	ChatID int64
	MsgID  int64
}

type CharacterAttr struct {
	UserID    int64
	AttrName  string
	AttrValue string
}

type ChatCfg struct {
	ID             int64
	WebID          sql.NullInt64
	AutoCvtBili    bool
	AutoOcr        bool
	AutoCalculate  bool
	AutoExchange   bool
	AutoCheckAdult bool
	SaveMessages   bool
	EnableCoc      bool
	RespNsfwMsg    bool
}

type PicRateCounter struct {
	Rate  int64
	Count int64
}

type PrprCach struct {
	ProfilePhotoUid string
	PrprFileID      string
}

type SavedPic struct {
	FileUid       string
	FileID        string
	BotRate       int64
	RandKey       int64
	UserRate      int64
	UserRatingSum int64
	RateUserCount int64
}

type SavedPicsRating struct {
	FileUid string
	UserID  int64
	Rating  int64
}

type User struct {
	ID              int64
	UpdatedAt       UnixTime
	UserID          int64
	FirstName       string
	LastName        sql.NullString
	ProfileUpdateAt UnixTime
	ProfilePhoto    sql.NullString
	TimeZone        sql.NullInt64
}

type YtDlResult struct {
	Url         string
	AudioOnly   bool
	Resolution  int64
	FileID      string
	Title       sql.NullString
	Description sql.NullString
	Uploader    sql.NullString
	UploadCount int64
}
