// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query_pics.sql

package q

import (
	"context"
	"time"

	"go.uber.org/zap"
)

const getPicByRateAndRandKey = `-- name: getPicByRateAndRandKey :one

SELECT file_id
FROM saved_pics
WHERE user_rate = ?
  AND rand_key > ?
LIMIT 1
`

// encoding: utf-8
func (q *Queries) getPicByRateAndRandKey(ctx context.Context, userRate int64, randKey int64) (string, error) {
	var logFields []zap.Field
	var start time.Time
	if q.logger != nil {
		logFields = make([]zap.Field, 0, 2+5)
		start = time.Now()
		logFields = append(logFields,
			zap.Int64("user_rate", userRate),
			zap.Int64("rand_key", randKey),
		)
	}
	row := q.queryRow(ctx, q.getPicByRateAndRandKeyStmt, getPicByRateAndRandKey, userRate, randKey)
	var file_id string
	err := row.Scan(&file_id)
	q.logQuery(getPicByRateAndRandKey, logFields, err, start)
	return file_id, err
}

const getPicByRateFirst = `-- name: getPicByRateFirst :one
SELECT file_id
FROM saved_pics
WHERE user_rate = ?
ORDER BY rand_key
LIMIT 1
`

func (q *Queries) getPicByRateFirst(ctx context.Context, userRate int64) (string, error) {
	var logFields []zap.Field
	var start time.Time
	if q.logger != nil {
		logFields = make([]zap.Field, 0, 1+5)
		start = time.Now()
		logFields = append(logFields,
			zap.Int64("user_rate", userRate),
		)
	}
	row := q.queryRow(ctx, q.getPicByRateFirstStmt, getPicByRateFirst, userRate)
	var file_id string
	err := row.Scan(&file_id)
	q.logQuery(getPicByRateFirst, logFields, err, start)
	return file_id, err
}

const getPicRateCounts = `-- name: getPicRateCounts :many
SELECT rate, count
FROM pic_rate_counter
ORDER BY rate
`

func (q *Queries) getPicRateCounts(ctx context.Context) ([]PicRateCounter, error) {
	var logFields []zap.Field
	var start time.Time
	if q.logger != nil {
		logFields = make([]zap.Field, 0, 0+5)
		start = time.Now()
	}
	rows, err := q.query(ctx, q.getPicRateCountsStmt, getPicRateCounts)
	if err != nil {
		q.logQuery(getPicRateCounts, logFields, err, start)
		return nil, err
	}
	defer rows.Close()
	var items []PicRateCounter
	for rows.Next() {
		var i PicRateCounter
		if err = rows.Scan(&i.Rate, &i.Count); err != nil {
			q.logQuery(getPicRateCounts, logFields, err, start)
			return nil, err
		}
		items = append(items, i)
	}
	if err = rows.Close(); err != nil {
		q.logQuery(getPicRateCounts, logFields, err, start)
		return nil, err
	}
	if err = rows.Err(); err != nil {
		q.logQuery(getPicRateCounts, logFields, err, start)
		return nil, err
	}
	q.logQuery(getPicRateCounts, logFields, err, start)
	return items, nil
}

const insertPic = `-- name: insertPic :one
INSERT INTO saved_pics (file_uid, file_id, bot_rate, rand_key, user_rate)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(file_uid) DO UPDATE SET file_id   = excluded.file_id,
                                    bot_rate  = excluded.bot_rate,
                                    user_rate =
                                        CASE
                                            WHEN excluded.rate_user_count = 0
                                                THEN excluded.bot_rate
                                            ELSE
                                                excluded.user_rate
                                            END
RETURNING file_uid, file_id, bot_rate, rand_key, user_rate, user_rating_sum, rate_user_count
`

type insertPicParams struct {
	FileUid  string `json:"file_uid"`
	FileID   string `json:"file_id"`
	BotRate  int64  `json:"bot_rate"`
	RandKey  int64  `json:"rand_key"`
	UserRate int64  `json:"user_rate"`
}

func (q *Queries) insertPic(ctx context.Context, arg insertPicParams) (SavedPic, error) {
	var logFields []zap.Field
	var start time.Time
	if q.logger != nil {
		logFields = make([]zap.Field, 0, 5+5)
		start = time.Now()
		logFields = append(logFields,
			zap.String("file_uid", arg.FileUid),
			zap.String("file_id", arg.FileID),
			zap.Int64("bot_rate", arg.BotRate),
			zap.Int64("rand_key", arg.RandKey),
			zap.Int64("user_rate", arg.UserRate),
		)
	}
	row := q.queryRow(ctx, q.insertPicStmt, insertPic,
		arg.FileUid,
		arg.FileID,
		arg.BotRate,
		arg.RandKey,
		arg.UserRate,
	)
	var i SavedPic
	err := row.Scan(
		&i.FileUid,
		&i.FileID,
		&i.BotRate,
		&i.RandKey,
		&i.UserRate,
		&i.UserRatingSum,
		&i.RateUserCount,
	)
	q.logQuery(insertPic, logFields, err, start)
	return i, err
}
