// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query_ytdl.sql

package q

import (
	"context"
	"time"

	"go.uber.org/zap"
)

const getYtDlpDbCache = `-- name: GetYtDlpDbCache :one

SELECT url, audio_only, resolution, file_id, title, description, uploader, upload_count
FROM yt_dl_results
WHERE url = ?
  AND audio_only = ?
  AND resolution = ?
`

// encoding: utf-8
func (q *Queries) GetYtDlpDbCache(ctx context.Context, url string, audioOnly bool, resolution int64) (YtDlResult, error) {
	var logFields []zap.Field
	var start time.Time
	if q.logger != nil {
		logFields = make([]zap.Field, 0, 6)
		start = time.Now()
		logFields = append(logFields,
			zap.Dict("fields",
				zap.String("url", url),
				zap.Bool("audio_only", audioOnly),
				zap.Int64("resolution", resolution),
			),
		)
	}
	row := q.queryRow(ctx, q.getYtDlpDbCacheStmt, getYtDlpDbCache, url, audioOnly, resolution)
	var i YtDlResult
	err := row.Scan(
		&i.Url,
		&i.AudioOnly,
		&i.Resolution,
		&i.FileID,
		&i.Title,
		&i.Description,
		&i.Uploader,
		&i.UploadCount,
	)
	q.logQuery(getYtDlpDbCache, logFields, err, start)
	return i, err
}

const incYtDlUploadCount = `-- name: IncYtDlUploadCount :exec
UPDATE yt_dl_results
SET upload_count=upload_count + 1
WHERE file_id = ?
`

func (q *Queries) IncYtDlUploadCount(ctx context.Context, fileID string) error {
	var logFields []zap.Field
	var start time.Time
	if q.logger != nil {
		logFields = make([]zap.Field, 0, 6)
		start = time.Now()
		logFields = append(logFields,
			zap.Dict("fields",
				zap.String("file_id", fileID),
			),
		)
	}
	_, err := q.exec(ctx, q.incYtDlUploadCountStmt, incYtDlUploadCount, fileID)
	q.logQuery(incYtDlUploadCount, logFields, err, start)
	return err
}

const updateYtDlpCache = `-- name: UpdateYtDlpCache :exec
INSERT INTO yt_dl_results
(url, audio_only, resolution, file_id, title, description, uploader, upload_count)
VALUES (?, ?, ?, ?, ?, ?, ?, 1)
ON CONFLICT DO UPDATE
    SET file_id=file_id,
        title=title,
        description=description,
        uploader=uploader
`

type UpdateYtDlpCacheParams struct {
	Url         string `json:"url"`
	AudioOnly   bool   `json:"audio_only"`
	Resolution  int64  `json:"resolution"`
	FileID      string `json:"file_id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	Uploader    string `json:"uploader"`
}

func (q *Queries) UpdateYtDlpCache(ctx context.Context, arg UpdateYtDlpCacheParams) error {
	var logFields []zap.Field
	var start time.Time
	if q.logger != nil {
		logFields = make([]zap.Field, 0, 6)
		start = time.Now()
		logFields = append(logFields,
			zap.Dict("fields",
				zap.String("url", arg.Url),
				zap.Bool("audio_only", arg.AudioOnly),
				zap.Int64("resolution", arg.Resolution),
				zap.String("file_id", arg.FileID),
				zap.String("title", arg.Title),
				zap.String("description", arg.Description),
				zap.String("uploader", arg.Uploader),
			),
		)
	}
	_, err := q.exec(ctx, q.updateYtDlpCacheStmt, updateYtDlpCache,
		arg.Url,
		arg.AudioOnly,
		arg.Resolution,
		arg.FileID,
		arg.Title,
		arg.Description,
		arg.Uploader,
	)
	q.logQuery(updateYtDlpCache, logFields, err, start)
	return err
}
