// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query_gemini.sql

package q

import (
	"context"
	"database/sql"
)

const addGeminiMessage = `-- name: AddGeminiMessage :exec
INSERT INTO gemini_contents (session_id,
                             chat_id,
                             msg_id,
                             role,
                             sent_time,
                             username,
                             msg_type,
                             reply_to_msg_id,
                             text,
                             blob,
                             mime_type,
                             quote_part,
                             thought_signature)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type AddGeminiMessageParams struct {
	SessionID        int64          `json:"session_id"`
	ChatID           int64          `json:"chat_id"`
	MsgID            int64          `json:"msg_id"`
	Role             string         `json:"role"`
	SentTime         UnixTime       `json:"sent_time"`
	Username         string         `json:"username"`
	MsgType          string         `json:"msg_type"`
	ReplyToMsgID     sql.NullInt64  `json:"reply_to_msg_id"`
	Text             sql.NullString `json:"text"`
	Blob             []byte         `json:"blob"`
	MimeType         sql.NullString `json:"mime_type"`
	QuotePart        sql.NullString `json:"quote_part"`
	ThoughtSignature sql.NullString `json:"thought_signature"`
}

func (q *Queries) AddGeminiMessage(ctx context.Context, arg AddGeminiMessageParams) error {
	_, err := q.exec(ctx, q.addGeminiMessageStmt, addGeminiMessage,
		arg.SessionID,
		arg.ChatID,
		arg.MsgID,
		arg.Role,
		arg.SentTime,
		arg.Username,
		arg.MsgType,
		arg.ReplyToMsgID,
		arg.Text,
		arg.Blob,
		arg.MimeType,
		arg.QuotePart,
		arg.ThoughtSignature,
	)
	return err
}

const createGeminiMemory = `-- name: CreateGeminiMemory :one
INSERT INTO gemini_memories (chat_id, topic_id, content)
VALUES (?, ?, ?)
RETURNING id, chat_id, topic_id, content
`

func (q *Queries) CreateGeminiMemory(ctx context.Context, chatID int64, topicID int64, content string) (GeminiMemory, error) {
	row := q.queryRow(ctx, q.createGeminiMemoryStmt, createGeminiMemory, chatID, topicID, content)
	var i GeminiMemory
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.TopicID,
		&i.Content,
	)
	return i, err
}

const createNewGeminiSession = `-- name: CreateNewGeminiSession :one

INSERT INTO gemini_sessions (chat_id, chat_name, chat_type)
VALUES (?, ?, ?)
RETURNING id, chat_id, chat_name, chat_type, frozen, total_input_tokens, total_output_tokens
`

// encoding: utf-8
func (q *Queries) CreateNewGeminiSession(ctx context.Context, chatID int64, chatName string, chatType string) (GeminiSession, error) {
	row := q.queryRow(ctx, q.createNewGeminiSessionStmt, createNewGeminiSession, chatID, chatName, chatType)
	var i GeminiSession
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.ChatName,
		&i.ChatType,
		&i.Frozen,
		&i.TotalInputTokens,
		&i.TotalOutputTokens,
	)
	return i, err
}

const createOrUpdateGeminiSystemPrompt = `-- name: CreateOrUpdateGeminiSystemPrompt :exec
INSERT INTO gemini_system_prompt (chat_id, thread_id, prompt)
VALUES (?, ?, ?)
ON CONFLICT DO UPDATE SET prompt=excluded.prompt
`

func (q *Queries) CreateOrUpdateGeminiSystemPrompt(ctx context.Context, chatID int64, threadID int64, prompt string) error {
	_, err := q.exec(ctx, q.createOrUpdateGeminiSystemPromptStmt, createOrUpdateGeminiSystemPrompt, chatID, threadID, prompt)
	return err
}

const deleteGeminiMemory = `-- name: DeleteGeminiMemory :exec
DELETE
FROM gemini_memories
WHERE id = ?
`

func (q *Queries) DeleteGeminiMemory(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.deleteGeminiMemoryStmt, deleteGeminiMemory, id)
	return err
}

const getGeminiSystemPrompt = `-- name: GetGeminiSystemPrompt :one
SELECT prompt
FROM gemini_system_prompt
WHERE chat_id = ?
  AND thread_id = ?
`

func (q *Queries) GetGeminiSystemPrompt(ctx context.Context, chatID int64, threadID int64) (string, error) {
	row := q.queryRow(ctx, q.getGeminiSystemPromptStmt, getGeminiSystemPrompt, chatID, threadID)
	var prompt string
	err := row.Scan(&prompt)
	return prompt, err
}

const getSessionById = `-- name: GetSessionById :one
SELECT id, chat_id, chat_name, chat_type, frozen, total_input_tokens, total_output_tokens
FROM gemini_sessions
WHERE id = ?
`

func (q *Queries) GetSessionById(ctx context.Context, id int64) (GeminiSession, error) {
	row := q.queryRow(ctx, q.getSessionByIdStmt, getSessionById, id)
	var i GeminiSession
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.ChatName,
		&i.ChatType,
		&i.Frozen,
		&i.TotalInputTokens,
		&i.TotalOutputTokens,
	)
	return i, err
}

const getSessionIdByMessage = `-- name: GetSessionIdByMessage :one
SELECT gemini_contents.session_id
FROM gemini_contents
WHERE chat_id = ?
  AND msg_id = ?
`

func (q *Queries) GetSessionIdByMessage(ctx context.Context, chatID int64, msgID int64) (int64, error) {
	row := q.queryRow(ctx, q.getSessionIdByMessageStmt, getSessionIdByMessage, chatID, msgID)
	var session_id int64
	err := row.Scan(&session_id)
	return session_id, err
}

const incrementSessionTokenCounters = `-- name: IncrementSessionTokenCounters :exec
UPDATE gemini_sessions
SET total_input_tokens = total_input_tokens + ?,
    total_output_tokens=total_output_tokens + ?
WHERE id = ?
`

func (q *Queries) IncrementSessionTokenCounters(ctx context.Context, totalInputTokens int64, totalOutputTokens int64, iD int64) error {
	_, err := q.exec(ctx, q.incrementSessionTokenCountersStmt, incrementSessionTokenCounters, totalInputTokens, totalOutputTokens, iD)
	return err
}

const listGeminiMemory = `-- name: ListGeminiMemory :many
SELECT id, chat_id, topic_id, content
FROM gemini_memories
WHERE chat_id = ?
  AND topic_id = ?
LIMIT ?
`

func (q *Queries) ListGeminiMemory(ctx context.Context, chatID int64, topicID int64, limit int64) ([]GeminiMemory, error) {
	rows, err := q.query(ctx, q.listGeminiMemoryStmt, listGeminiMemory, chatID, topicID, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GeminiMemory
	for rows.Next() {
		var i GeminiMemory
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.TopicID,
			&i.Content,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetGeminiSystemPrompt = `-- name: ResetGeminiSystemPrompt :exec
DELETE
FROM gemini_system_prompt
WHERE chat_id = ?
  AND thread_id = ?
`

func (q *Queries) ResetGeminiSystemPrompt(ctx context.Context, chatID int64, threadID int64) error {
	_, err := q.exec(ctx, q.resetGeminiSystemPromptStmt, resetGeminiSystemPrompt, chatID, threadID)
	return err
}

const updateGeminiMemory = `-- name: UpdateGeminiMemory :exec
UPDATE gemini_memories
SET content=?2
WHERE id = ?1
`

func (q *Queries) UpdateGeminiMemory(ctx context.Context, iD int64, content string) error {
	_, err := q.exec(ctx, q.updateGeminiMemoryStmt, updateGeminiMemory, iD, content)
	return err
}

const getAllMsgInSessionReversed = `-- name: getAllMsgInSessionReversed :many
SELECT session_id, chat_id, msg_id, role, sent_time, username, msg_type, reply_to_msg_id, text, blob, mime_type, quote_part, thought_signature, atable_username, user_id
FROM gemini_contents
WHERE session_id = ?
ORDER BY msg_id DESC
LIMIT ?
`

func (q *Queries) getAllMsgInSessionReversed(ctx context.Context, sessionID int64, limit int64) ([]GeminiContent, error) {
	rows, err := q.query(ctx, q.getAllMsgInSessionReversedStmt, getAllMsgInSessionReversed, sessionID, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GeminiContent
	for rows.Next() {
		var i GeminiContent
		if err := rows.Scan(
			&i.SessionID,
			&i.ChatID,
			&i.MsgID,
			&i.Role,
			&i.SentTime,
			&i.Username,
			&i.MsgType,
			&i.ReplyToMsgID,
			&i.Text,
			&i.Blob,
			&i.MimeType,
			&i.QuotePart,
			&i.ThoughtSignature,
			&i.AtableUsername,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
