// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query_chat.sql

package q

import (
	"context"
	"database/sql"
	"time"

	"go.uber.org/zap"
)

const updateChatStatDaily = `-- name: UpdateChatStatDaily :exec
UPDATE chat_stat_daily
SET message_count        = ?,
    photo_count          = ?,
    video_count          = ?,
    sticker_count        = ?,
    forward_count        = ?,
    mars_count           = ?,
    max_mars_count       = ?,
    racy_count           = ?,
    adult_count          = ?,
    download_video_count = ?,
    download_audio_count = ?,
    dio_add_user_count   = ?,
    dio_ban_user_count   = ?,
    user_msg_stat        = ?,
    msg_count_by_time    = ?,
    msg_id_at_time_start = ?
WHERE chat_id = ?
  AND stat_date = ?
`

type UpdateChatStatDailyParams struct {
	MessageCount       int64          `json:"message_count"`
	PhotoCount         int64          `json:"photo_count"`
	VideoCount         int64          `json:"video_count"`
	StickerCount       int64          `json:"sticker_count"`
	ForwardCount       int64          `json:"forward_count"`
	MarsCount          int64          `json:"mars_count"`
	MaxMarsCount       int64          `json:"max_mars_count"`
	RacyCount          int64          `json:"racy_count"`
	AdultCount         int64          `json:"adult_count"`
	DownloadVideoCount int64          `json:"download_video_count"`
	DownloadAudioCount int64          `json:"download_audio_count"`
	DioAddUserCount    int64          `json:"dio_add_user_count"`
	DioBanUserCount    int64          `json:"dio_ban_user_count"`
	UserMsgStat        UserMsgStatMap `json:"user_msg_stat"`
	MsgCountByTime     TenMinuteStats `json:"msg_count_by_time"`
	MsgIDAtTimeStart   TenMinuteStats `json:"msg_id_at_time_start"`
	ChatID             int64          `json:"chat_id"`
	StatDate           int64          `json:"stat_date"`
}

func (q *Queries) UpdateChatStatDaily(ctx context.Context, arg UpdateChatStatDailyParams) error {
	var logFields []zap.Field
	var start time.Time
	if q.logger != nil {
		logFields = make([]zap.Field, 0, 18+5)
		start = time.Now()
		logFields = append(logFields,
			zap.Int64("message_count", arg.MessageCount),
			zap.Int64("photo_count", arg.PhotoCount),
			zap.Int64("video_count", arg.VideoCount),
			zap.Int64("sticker_count", arg.StickerCount),
			zap.Int64("forward_count", arg.ForwardCount),
			zap.Int64("mars_count", arg.MarsCount),
			zap.Int64("max_mars_count", arg.MaxMarsCount),
			zap.Int64("racy_count", arg.RacyCount),
			zap.Int64("adult_count", arg.AdultCount),
			zap.Int64("download_video_count", arg.DownloadVideoCount),
			zap.Int64("download_audio_count", arg.DownloadAudioCount),
			zap.Int64("dio_add_user_count", arg.DioAddUserCount),
			zap.Int64("dio_ban_user_count", arg.DioBanUserCount),
			zap.Any("user_msg_stat", arg.UserMsgStat),
			zap.Any("msg_count_by_time", arg.MsgCountByTime),
			zap.Any("msg_id_at_time_start", arg.MsgIDAtTimeStart),
			zap.Int64("chat_id", arg.ChatID),
			zap.Int64("stat_date", arg.StatDate),
		)
	}
	_, err := q.exec(ctx, q.updateChatStatDailyStmt, updateChatStatDaily,
		arg.MessageCount,
		arg.PhotoCount,
		arg.VideoCount,
		arg.StickerCount,
		arg.ForwardCount,
		arg.MarsCount,
		arg.MaxMarsCount,
		arg.RacyCount,
		arg.AdultCount,
		arg.DownloadVideoCount,
		arg.DownloadAudioCount,
		arg.DioAddUserCount,
		arg.DioBanUserCount,
		arg.UserMsgStat,
		arg.MsgCountByTime,
		arg.MsgIDAtTimeStart,
		arg.ChatID,
		arg.StatDate,
	)
	q.logQuery(updateChatStatDaily, logFields, err, start)
	return err
}

const chatCfgById = `-- name: chatCfgById :one

SELECT id, web_id, auto_cvt_bili, auto_ocr, auto_calculate, auto_exchange, auto_check_adult, save_messages, enable_coc, resp_nsfw_msg, timezone
FROM chat_cfg
WHERE id = ?
`

// encoding: utf-8
func (q *Queries) chatCfgById(ctx context.Context, id int64) (chatCfg, error) {
	var logFields []zap.Field
	var start time.Time
	if q.logger != nil {
		logFields = make([]zap.Field, 0, 1+5)
		start = time.Now()
		logFields = append(logFields,
			zap.Int64("id", id),
		)
	}
	row := q.queryRow(ctx, q.chatCfgByIdStmt, chatCfgById, id)
	var i chatCfg
	err := row.Scan(
		&i.ID,
		&i.WebID,
		&i.AutoCvtBili,
		&i.AutoOcr,
		&i.AutoCalculate,
		&i.AutoExchange,
		&i.AutoCheckAdult,
		&i.SaveMessages,
		&i.EnableCoc,
		&i.RespNsfwMsg,
		&i.Timezone,
	)
	q.logQuery(chatCfgById, logFields, err, start)
	return i, err
}

const chatIdByWebId = `-- name: chatIdByWebId :one
SELECT id
FROM chat_cfg
WHERE web_id = ?
`

func (q *Queries) chatIdByWebId(ctx context.Context, webID sql.NullInt64) (int64, error) {
	var logFields []zap.Field
	var start time.Time
	if q.logger != nil {
		logFields = make([]zap.Field, 0, 1+5)
		start = time.Now()
		logFields = append(logFields,
			zapNullInt64("web_id", webID),
		)
	}
	row := q.queryRow(ctx, q.chatIdByWebIdStmt, chatIdByWebId, webID)
	var id int64
	err := row.Scan(&id)
	q.logQuery(chatIdByWebId, logFields, err, start)
	return id, err
}

const createChatStatDaily = `-- name: createChatStatDaily :one
INSERT INTO chat_stat_daily (chat_id, stat_date)
VALUES (?, ?)
RETURNING chat_id, stat_date, message_count, photo_count, video_count, sticker_count, forward_count, mars_count, max_mars_count, racy_count, adult_count, download_video_count, download_audio_count, dio_add_user_count, dio_ban_user_count, user_msg_stat, msg_count_by_time, msg_id_at_time_start
`

func (q *Queries) createChatStatDaily(ctx context.Context, chatID int64, statDate int64) (ChatStatDaily, error) {
	var logFields []zap.Field
	var start time.Time
	if q.logger != nil {
		logFields = make([]zap.Field, 0, 2+5)
		start = time.Now()
		logFields = append(logFields,
			zap.Int64("chat_id", chatID),
			zap.Int64("stat_date", statDate),
		)
	}
	row := q.queryRow(ctx, q.createChatStatDailyStmt, createChatStatDaily, chatID, statDate)
	var i ChatStatDaily
	err := row.Scan(
		&i.ChatID,
		&i.StatDate,
		&i.MessageCount,
		&i.PhotoCount,
		&i.VideoCount,
		&i.StickerCount,
		&i.ForwardCount,
		&i.MarsCount,
		&i.MaxMarsCount,
		&i.RacyCount,
		&i.AdultCount,
		&i.DownloadVideoCount,
		&i.DownloadAudioCount,
		&i.DioAddUserCount,
		&i.DioBanUserCount,
		&i.UserMsgStat,
		&i.MsgCountByTime,
		&i.MsgIDAtTimeStart,
	)
	q.logQuery(createChatStatDaily, logFields, err, start)
	return i, err
}

const createNewChatCfgDefault = `-- name: createNewChatCfgDefault :one
INSERT INTO chat_cfg (id, web_id, auto_cvt_bili, auto_ocr, auto_calculate, auto_exchange, auto_check_adult,
                      save_messages, enable_coc, resp_nsfw_msg, timezone)
VALUES (?,
        NULL,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        TRUE,
        FALSE,
        FALSE,
        0)
RETURNING id, web_id, auto_cvt_bili, auto_ocr, auto_calculate, auto_exchange, auto_check_adult, save_messages, enable_coc, resp_nsfw_msg, timezone
`

func (q *Queries) createNewChatCfgDefault(ctx context.Context, id int64) (chatCfg, error) {
	var logFields []zap.Field
	var start time.Time
	if q.logger != nil {
		logFields = make([]zap.Field, 0, 1+5)
		start = time.Now()
		logFields = append(logFields,
			zap.Int64("id", id),
		)
	}
	row := q.queryRow(ctx, q.createNewChatCfgDefaultStmt, createNewChatCfgDefault, id)
	var i chatCfg
	err := row.Scan(
		&i.ID,
		&i.WebID,
		&i.AutoCvtBili,
		&i.AutoOcr,
		&i.AutoCalculate,
		&i.AutoExchange,
		&i.AutoCheckAdult,
		&i.SaveMessages,
		&i.EnableCoc,
		&i.RespNsfwMsg,
		&i.Timezone,
	)
	q.logQuery(createNewChatCfgDefault, logFields, err, start)
	return i, err
}

const getChatStat = `-- name: getChatStat :one
SELECT chat_id, stat_date, message_count, photo_count, video_count, sticker_count, forward_count, mars_count, max_mars_count, racy_count, adult_count, download_video_count, download_audio_count, dio_add_user_count, dio_ban_user_count, user_msg_stat, msg_count_by_time, msg_id_at_time_start
FROM chat_stat_daily
WHERE chat_stat_daily.chat_id = ?
  AND chat_stat_daily.stat_date = ?
`

func (q *Queries) getChatStat(ctx context.Context, chatID int64, statDate int64) (ChatStatDaily, error) {
	var logFields []zap.Field
	var start time.Time
	if q.logger != nil {
		logFields = make([]zap.Field, 0, 2+5)
		start = time.Now()
		logFields = append(logFields,
			zap.Int64("chat_id", chatID),
			zap.Int64("stat_date", statDate),
		)
	}
	row := q.queryRow(ctx, q.getChatStatStmt, getChatStat, chatID, statDate)
	var i ChatStatDaily
	err := row.Scan(
		&i.ChatID,
		&i.StatDate,
		&i.MessageCount,
		&i.PhotoCount,
		&i.VideoCount,
		&i.StickerCount,
		&i.ForwardCount,
		&i.MarsCount,
		&i.MaxMarsCount,
		&i.RacyCount,
		&i.AdultCount,
		&i.DownloadVideoCount,
		&i.DownloadAudioCount,
		&i.DioAddUserCount,
		&i.DioBanUserCount,
		&i.UserMsgStat,
		&i.MsgCountByTime,
		&i.MsgIDAtTimeStart,
	)
	q.logQuery(getChatStat, logFields, err, start)
	return i, err
}

const updateChatCfg = `-- name: updateChatCfg :exec
UPDATE chat_cfg
SET auto_cvt_bili=?,
    auto_ocr=?,
    auto_calculate=?,
    auto_exchange=?,
    auto_check_adult=?,
    save_messages=?,
    enable_coc=?,
    resp_nsfw_msg=?
WHERE id = ?
`

type updateChatCfgParams struct {
	AutoCvtBili    bool  `json:"auto_cvt_bili"`
	AutoOcr        bool  `json:"auto_ocr"`
	AutoCalculate  bool  `json:"auto_calculate"`
	AutoExchange   bool  `json:"auto_exchange"`
	AutoCheckAdult bool  `json:"auto_check_adult"`
	SaveMessages   bool  `json:"save_messages"`
	EnableCoc      bool  `json:"enable_coc"`
	RespNsfwMsg    bool  `json:"resp_nsfw_msg"`
	ID             int64 `json:"id"`
}

func (q *Queries) updateChatCfg(ctx context.Context, arg updateChatCfgParams) error {
	var logFields []zap.Field
	var start time.Time
	if q.logger != nil {
		logFields = make([]zap.Field, 0, 9+5)
		start = time.Now()
		logFields = append(logFields,
			zap.Bool("auto_cvt_bili", arg.AutoCvtBili),
			zap.Bool("auto_ocr", arg.AutoOcr),
			zap.Bool("auto_calculate", arg.AutoCalculate),
			zap.Bool("auto_exchange", arg.AutoExchange),
			zap.Bool("auto_check_adult", arg.AutoCheckAdult),
			zap.Bool("save_messages", arg.SaveMessages),
			zap.Bool("enable_coc", arg.EnableCoc),
			zap.Bool("resp_nsfw_msg", arg.RespNsfwMsg),
			zap.Int64("id", arg.ID),
		)
	}
	_, err := q.exec(ctx, q.updateChatCfgStmt, updateChatCfg,
		arg.AutoCvtBili,
		arg.AutoOcr,
		arg.AutoCalculate,
		arg.AutoExchange,
		arg.AutoCheckAdult,
		arg.SaveMessages,
		arg.EnableCoc,
		arg.RespNsfwMsg,
		arg.ID,
	)
	q.logQuery(updateChatCfg, logFields, err, start)
	return err
}
