// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query_bilibili.sql

package q

import (
	"context"
)

const getBiliInlineData = `-- name: GetBiliInlineData :one

SELECT text, chat_id, msg_id
FROM bili_inline_results
WHERE uid = ?
`

type GetBiliInlineDataRow struct {
	Text   string `json:"text"`
	ChatID int64  `json:"chat_id"`
	MsgID  int64  `json:"msg_id"`
}

// encoding: utf-8
func (q *Queries) GetBiliInlineData(ctx context.Context, uid int64) (GetBiliInlineDataRow, error) {
	row := q.db.QueryRowContext(ctx, getBiliInlineData, uid)
	var i GetBiliInlineDataRow
	err := row.Scan(&i.Text, &i.ChatID, &i.MsgID)
	return i, err
}

const insertBiliInlineData = `-- name: InsertBiliInlineData :one
INSERT INTO bili_inline_results
    DEFAULT
VALUES
RETURNING uid
`

func (q *Queries) InsertBiliInlineData(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertBiliInlineData)
	var uid int64
	err := row.Scan(&uid)
	return uid, err
}

const updateBiliInlineMsgId = `-- name: UpdateBiliInlineMsgId :exec
UPDATE bili_inline_results
SET text    = ?,
    chat_id = ?,
    msg_id  = ?
WHERE uid = ?
`

func (q *Queries) UpdateBiliInlineMsgId(ctx context.Context, text string, chatID int64, msgID int64, uid int64) error {
	_, err := q.db.ExecContext(ctx, updateBiliInlineMsgId,
		text,
		chatID,
		msgID,
		uid,
	)
	return err
}
