// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query_ytdl.sql

package q

import (
	"context"
	"database/sql"
)

const getYtDlpDbCache = `-- name: GetYtDlpDbCache :one

SELECT url, audio_only, resolution, file_id, title, description, uploader, upload_count
FROM yt_dl_results
WHERE url = ?
  AND audio_only = ?
  AND resolution = ?
`

// encoding: utf-8
func (q *Queries) GetYtDlpDbCache(ctx context.Context, url string, audioOnly bool, resolution int64) (YtDlResult, error) {
	row := q.db.QueryRowContext(ctx, getYtDlpDbCache, url, audioOnly, resolution)
	var i YtDlResult
	err := row.Scan(
		&i.Url,
		&i.AudioOnly,
		&i.Resolution,
		&i.FileID,
		&i.Title,
		&i.Description,
		&i.Uploader,
		&i.UploadCount,
	)
	return i, err
}

const updateYtDlpCache = `-- name: UpdateYtDlpCache :exec
INSERT INTO yt_dl_results
(url, audio_only, resolution, file_id, title, description, uploader, upload_count)
VALUES (?, ?, ?, ?, ?, ?, ?, 1)
ON CONFLICT DO UPDATE
    SET file_id=file_id,
        title=title,
        description=description,
        uploader=uploader
`

type UpdateYtDlpCacheParams struct {
	Url         string
	AudioOnly   bool
	Resolution  int64
	FileID      string
	Title       sql.NullString
	Description sql.NullString
	Uploader    sql.NullString
}

func (q *Queries) UpdateYtDlpCache(ctx context.Context, arg UpdateYtDlpCacheParams) error {
	_, err := q.db.ExecContext(ctx, updateYtDlpCache,
		arg.Url,
		arg.AudioOnly,
		arg.Resolution,
		arg.FileID,
		arg.Title,
		arg.Description,
		arg.Uploader,
	)
	return err
}

const uploadYtDlpByFileId = `-- name: UploadYtDlpByFileId :exec
UPDATE yt_dl_results
SET upload_count=upload_count + 1
WHERE file_id = ?
`

func (q *Queries) UploadYtDlpByFileId(ctx context.Context, fileID string) error {
	_, err := q.db.ExecContext(ctx, uploadYtDlpByFileId, fileID)
	return err
}
