// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query_pics.sql

package q

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getNsfwPicByFileUid = `-- name: GetNsfwPicByFileUid :one
SELECT file_uid, file_id, bot_rate, rand_key, user_rate, user_rating_sum, rate_user_count
FROM saved_pics
WHERE file_uid = $1
`

func (q *Queries) GetNsfwPicByFileUid(ctx context.Context, fileUid string) (SavedPic, error) {
	row := q.db.QueryRow(ctx, getNsfwPicByFileUid, fileUid)
	var i SavedPic
	err := row.Scan(
		&i.FileUid,
		&i.FileID,
		&i.BotRate,
		&i.RandKey,
		&i.UserRate,
		&i.UserRatingSum,
		&i.RateUserCount,
	)
	return i, err
}

const listNsfwPicUserRatesByFileUid = `-- name: ListNsfwPicUserRatesByFileUid :many
SELECT rating, COUNT(*)
FROM saved_pics_rating
WHERE file_uid = $1
GROUP BY rating
`

type ListNsfwPicUserRatesByFileUidRow struct {
	Rating int32 `json:"rating"`
	Count  int64 `json:"count"`
}

func (q *Queries) ListNsfwPicUserRatesByFileUid(ctx context.Context, fileUid string) ([]ListNsfwPicUserRatesByFileUidRow, error) {
	rows, err := q.db.Query(ctx, listNsfwPicUserRatesByFileUid, fileUid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNsfwPicUserRatesByFileUidRow
	for rows.Next() {
		var i ListNsfwPicUserRatesByFileUidRow
		if err := rows.Scan(&i.Rating, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createNsfwPicUserRate = `-- name: createNsfwPicUserRate :exec
INSERT INTO saved_pics_rating (file_uid, user_id, rating)
VALUES ($1, $2, $3)
`

func (q *Queries) createNsfwPicUserRate(ctx context.Context, fileUid string, userID int64, rating int32) error {
	_, err := q.db.Exec(ctx, createNsfwPicUserRate, fileUid, userID, rating)
	return err
}

const createOrUpdateNsfwPic = `-- name: createOrUpdateNsfwPic :one
INSERT INTO saved_pics (file_uid, file_id, bot_rate, rand_key)
VALUES ($1, $2, $3, $4)
ON CONFLICT(file_uid) DO UPDATE SET file_id   = excluded.file_id,
                                    bot_rate  = excluded.bot_rate
RETURNING file_uid, file_id, bot_rate, rand_key, user_rate, user_rating_sum, rate_user_count
`

func (q *Queries) createOrUpdateNsfwPic(ctx context.Context, fileUid string, fileID string, botRate int32, randKey int64) (SavedPic, error) {
	row := q.db.QueryRow(ctx, createOrUpdateNsfwPic,
		fileUid,
		fileID,
		botRate,
		randKey,
	)
	var i SavedPic
	err := row.Scan(
		&i.FileUid,
		&i.FileID,
		&i.BotRate,
		&i.RandKey,
		&i.UserRate,
		&i.UserRatingSum,
		&i.RateUserCount,
	)
	return i, err
}

const getNsfwPicByRateAndRandKey = `-- name: getNsfwPicByRateAndRandKey :one

SELECT file_uid, file_id, bot_rate, rand_key, user_rate, user_rating_sum, rate_user_count
FROM saved_pics
WHERE user_rate = $1
  AND rand_key > $2
LIMIT 1
`

// encoding: utf-8
func (q *Queries) getNsfwPicByRateAndRandKey(ctx context.Context, userRate pgtype.Int4, randKey int64) (SavedPic, error) {
	row := q.db.QueryRow(ctx, getNsfwPicByRateAndRandKey, userRate, randKey)
	var i SavedPic
	err := row.Scan(
		&i.FileUid,
		&i.FileID,
		&i.BotRate,
		&i.RandKey,
		&i.UserRate,
		&i.UserRatingSum,
		&i.RateUserCount,
	)
	return i, err
}

const getNsfwPicByRateFirst = `-- name: getNsfwPicByRateFirst :one
SELECT file_uid, file_id, bot_rate, rand_key, user_rate, user_rating_sum, rate_user_count
FROM saved_pics
WHERE user_rate = $1
ORDER BY rand_key
LIMIT 1
`

func (q *Queries) getNsfwPicByRateFirst(ctx context.Context, userRate pgtype.Int4) (SavedPic, error) {
	row := q.db.QueryRow(ctx, getNsfwPicByRateFirst, userRate)
	var i SavedPic
	err := row.Scan(
		&i.FileUid,
		&i.FileID,
		&i.BotRate,
		&i.RandKey,
		&i.UserRate,
		&i.UserRatingSum,
		&i.RateUserCount,
	)
	return i, err
}

const getNsfwPicRateByUserId = `-- name: getNsfwPicRateByUserId :one
SELECT rating
FROM saved_pics_rating
WHERE file_uid = $1
  AND user_id = $2
`

func (q *Queries) getNsfwPicRateByUserId(ctx context.Context, fileUid string, userID int64) (int32, error) {
	row := q.db.QueryRow(ctx, getNsfwPicRateByUserId, fileUid, userID)
	var rating int32
	err := row.Scan(&rating)
	return rating, err
}

const listNsfwPicRateCounter = `-- name: listNsfwPicRateCounter :many
SELECT rate, count
FROM pic_rate_counter
ORDER BY rate
`

func (q *Queries) listNsfwPicRateCounter(ctx context.Context) ([]PicRateCounter, error) {
	rows, err := q.db.Query(ctx, listNsfwPicRateCounter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PicRateCounter
	for rows.Next() {
		var i PicRateCounter
		if err := rows.Scan(&i.Rate, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNsfwPicUserRate = `-- name: updateNsfwPicUserRate :exec
UPDATE saved_pics_rating
SET rating=$1
WHERE file_uid = $2
  AND user_id = $3
`

func (q *Queries) updateNsfwPicUserRate(ctx context.Context, rating int32, fileUid string, userID int64) error {
	_, err := q.db.Exec(ctx, updateNsfwPicUserRate, rating, fileUid, userID)
	return err
}
