// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query_user.sql

package q

import (
	"context"
	"database/sql"
)

const getPrprCache = `-- name: GetPrprCache :one
SELECT prpr_file_id
FROM prpr_caches
WHERE profile_photo_uid = $1
`

func (q *Queries) GetPrprCache(ctx context.Context, profilePhotoUid string) (string, error) {
	row := q.db.QueryRow(ctx, getPrprCache, profilePhotoUid)
	var prpr_file_id string
	err := row.Scan(&prpr_file_id)
	return prpr_file_id, err
}

const setPrprCache = `-- name: SetPrprCache :exec
INSERT INTO prpr_caches (profile_photo_uid, prpr_file_id)
VALUES ($1, $2)
`

func (q *Queries) SetPrprCache(ctx context.Context, profilePhotoUid string, prprFileID string) error {
	_, err := q.db.Exec(ctx, setPrprCache, profilePhotoUid, prprFileID)
	return err
}

const createNewUser = `-- name: createNewUser :one
INSERT INTO users (updated_at, user_id, first_name, last_name, profile_update_at, profile_photo, timezone)
VALUES ($1, $2, $3, $4, $1, $5, $6)
RETURNING id
`

type createNewUserParams struct {
	UpdatedAt    UnixTime       `json:"updated_at"`
	UserID       int64          `json:"user_id"`
	FirstName    string         `json:"first_name"`
	LastName     sql.NullString `json:"last_name"`
	ProfilePhoto sql.NullString `json:"profile_photo"`
	Timezone     int32          `json:"timezone"`
}

func (q *Queries) createNewUser(ctx context.Context, arg createNewUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, createNewUser,
		arg.UpdatedAt,
		arg.UserID,
		arg.FirstName,
		arg.LastName,
		arg.ProfilePhoto,
		arg.Timezone,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getUserById = `-- name: getUserById :one

SELECT id, updated_at, user_id, first_name, last_name, profile_update_at, profile_photo, timezone
FROM users
WHERE user_id = $1
`

// encoding: utf-8
func (q *Queries) getUserById(ctx context.Context, userID int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserById, userID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UpdatedAt,
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.ProfileUpdateAt,
		&i.ProfilePhoto,
		&i.Timezone,
	)
	return i, err
}

const updateUserBase = `-- name: updateUserBase :one
UPDATE users
SET updated_at=$2,
    first_name=$3,
    last_name =$4
WHERE user_id = $1
RETURNING id
`

func (q *Queries) updateUserBase(ctx context.Context, userID int64, updatedAt UnixTime, firstName string, lastName sql.NullString) (int64, error) {
	row := q.db.QueryRow(ctx, updateUserBase,
		userID,
		updatedAt,
		firstName,
		lastName,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const updateUserProfilePhoto = `-- name: updateUserProfilePhoto :exec
UPDATE users
SET profile_update_at = $2,
    profile_photo     = $3
WHERE user_id = $1
`

func (q *Queries) updateUserProfilePhoto(ctx context.Context, userID int64, profileUpdateAt UnixTime, profilePhoto sql.NullString) error {
	_, err := q.db.Exec(ctx, updateUserProfilePhoto, userID, profileUpdateAt, profilePhoto)
	return err
}

const updateUserTimeZone = `-- name: updateUserTimeZone :exec
UPDATE users
SET timezone = $2
WHERE user_id = $1
RETURNING id
`

func (q *Queries) updateUserTimeZone(ctx context.Context, userID int64, timezone int32) error {
	_, err := q.db.Exec(ctx, updateUserTimeZone, userID, timezone)
	return err
}
