// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query_chat.sql

package q

import (
	"context"
	"database/sql"
)

const createNewChatDefaultCfg = `-- name: CreateNewChatDefaultCfg :one
INSERT INTO chat_cfg (id, web_id, auto_cvt_bili, auto_ocr, auto_calculate, auto_exchange, auto_check_adult,
                      save_messages, enable_coc, resp_nsfw_msg)
VALUES (?,
        NULL,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        TRUE,
        FALSE,
        FALSE)
RETURNING id, web_id, auto_cvt_bili, auto_ocr, auto_calculate, auto_exchange, auto_check_adult, save_messages, enable_coc, resp_nsfw_msg
`

func (q *Queries) CreateNewChatDefaultCfg(ctx context.Context, id int64) (chatCfg, error) {
	row := q.db.QueryRowContext(ctx, createNewChatDefaultCfg, id)
	var i chatCfg
	err := row.Scan(
		&i.ID,
		&i.WebID,
		&i.AutoCvtBili,
		&i.AutoOcr,
		&i.AutoCalculate,
		&i.AutoExchange,
		&i.AutoCheckAdult,
		&i.SaveMessages,
		&i.EnableCoc,
		&i.RespNsfwMsg,
	)
	return i, err
}

const getChatById = `-- name: getChatById :one

SELECT id, web_id, auto_cvt_bili, auto_ocr, auto_calculate, auto_exchange, auto_check_adult, save_messages, enable_coc, resp_nsfw_msg
FROM chat_cfg
WHERE id = ?
`

// encoding: utf-8
func (q *Queries) getChatById(ctx context.Context, id int64) (chatCfg, error) {
	row := q.db.QueryRowContext(ctx, getChatById, id)
	var i chatCfg
	err := row.Scan(
		&i.ID,
		&i.WebID,
		&i.AutoCvtBili,
		&i.AutoOcr,
		&i.AutoCalculate,
		&i.AutoExchange,
		&i.AutoCheckAdult,
		&i.SaveMessages,
		&i.EnableCoc,
		&i.RespNsfwMsg,
	)
	return i, err
}

const getChatIdByWebId = `-- name: getChatIdByWebId :one
SELECT id
FROM chat_cfg
WHERE web_id = ?
`

func (q *Queries) getChatIdByWebId(ctx context.Context, webID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getChatIdByWebId, webID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const updateChat = `-- name: updateChat :exec
UPDATE chat_cfg
SET auto_cvt_bili=?,
    auto_ocr=?,
    auto_calculate=?,
    auto_exchange=?,
    auto_check_adult=?,
    save_messages=?,
    enable_coc=?,
    resp_nsfw_msg=?
WHERE id = ?
`

type updateChatParams struct {
	AutoCvtBili    bool  `json:"auto_cvt_bili"`
	AutoOcr        bool  `json:"auto_ocr"`
	AutoCalculate  bool  `json:"auto_calculate"`
	AutoExchange   bool  `json:"auto_exchange"`
	AutoCheckAdult bool  `json:"auto_check_adult"`
	SaveMessages   bool  `json:"save_messages"`
	EnableCoc      bool  `json:"enable_coc"`
	RespNsfwMsg    bool  `json:"resp_nsfw_msg"`
	ID             int64 `json:"id"`
}

func (q *Queries) updateChat(ctx context.Context, arg updateChatParams) error {
	_, err := q.db.ExecContext(ctx, updateChat,
		arg.AutoCvtBili,
		arg.AutoOcr,
		arg.AutoCalculate,
		arg.AutoExchange,
		arg.AutoCheckAdult,
		arg.SaveMessages,
		arg.EnableCoc,
		arg.RespNsfwMsg,
		arg.ID,
	)
	return err
}
