// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query_coc.sql

package q

import (
	"context"
	"time"

	"go.uber.org/zap"
)

const delCocCharAttr = `-- name: DelCocCharAttr :exec
DELETE
FROM character_attrs
WHERE user_id = ?
  AND attr_name = ?
`

func (q *Queries) DelCocCharAttr(ctx context.Context, userID int64, attrName string) error {
	var logFields []zap.Field
	var start time.Time
	if q.logger != nil {
		logFields = make([]zap.Field, 0, 6)
		start = time.Now()
		logFields = append(logFields,
			zap.Dict("fields",
				zap.Int64("user_id", userID),
				zap.String("attr_name", attrName),
			),
		)
	}
	_, err := q.exec(ctx, q.delCocCharAttrStmt, delCocCharAttr, userID, attrName)
	q.logQuery(delCocCharAttr, logFields, err, start)
	return err
}

const getCocCharAllAttr = `-- name: GetCocCharAllAttr :many
SELECT attr_name, attr_value
FROM character_attrs
WHERE user_id = ?
`

type GetCocCharAllAttrRow struct {
	AttrName  string `json:"attr_name"`
	AttrValue string `json:"attr_value"`
}

func (q *Queries) GetCocCharAllAttr(ctx context.Context, userID int64) ([]GetCocCharAllAttrRow, error) {
	var logFields []zap.Field
	var start time.Time
	if q.logger != nil {
		logFields = make([]zap.Field, 0, 6)
		start = time.Now()
		logFields = append(logFields,
			zap.Dict("fields",
				zap.Int64("user_id", userID),
			),
		)
	}
	rows, err := q.query(ctx, q.getCocCharAllAttrStmt, getCocCharAllAttr, userID)
	defer func() {
		q.logQuery(getCocCharAllAttr, logFields, err, start)
	}()
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCocCharAllAttrRow
	for rows.Next() {
		var i GetCocCharAllAttrRow
		if err = rows.Scan(&i.AttrName, &i.AttrValue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err = rows.Close(); err != nil {
		return nil, err
	}
	if err = rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCocCharAttr = `-- name: GetCocCharAttr :one

SELECT attr_value
FROM character_attrs
WHERE user_id = ?
  AND attr_name = ?
`

// encoding: utf-8
func (q *Queries) GetCocCharAttr(ctx context.Context, userID int64, attrName string) (string, error) {
	var logFields []zap.Field
	var start time.Time
	if q.logger != nil {
		logFields = make([]zap.Field, 0, 6)
		start = time.Now()
		logFields = append(logFields,
			zap.Dict("fields",
				zap.Int64("user_id", userID),
				zap.String("attr_name", attrName),
			),
		)
	}
	row := q.queryRow(ctx, q.getCocCharAttrStmt, getCocCharAttr, userID, attrName)
	var attr_value string
	err := row.Scan(&attr_value)
	q.logQuery(getCocCharAttr, logFields, err, start)
	return attr_value, err
}

const setCocCharAttr = `-- name: SetCocCharAttr :exec
INSERT INTO character_attrs
    (user_id, attr_name, attr_value)
VALUES (?, ?, ?)
ON CONFLICT DO UPDATE SET attr_value=excluded.attr_value
`

func (q *Queries) SetCocCharAttr(ctx context.Context, userID int64, attrName string, attrValue string) error {
	var logFields []zap.Field
	var start time.Time
	if q.logger != nil {
		logFields = make([]zap.Field, 0, 6)
		start = time.Now()
		logFields = append(logFields,
			zap.Dict("fields",
				zap.Int64("user_id", userID),
				zap.String("attr_name", attrName),
				zap.String("attr_value", attrValue),
			),
		)
	}
	_, err := q.exec(ctx, q.setCocCharAttrStmt, setCocCharAttr, userID, attrName, attrValue)
	q.logQuery(setCocCharAttr, logFields, err, start)
	return err
}
