// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query_ytdl.sql

package q

import (
	"context"
)

const getYtDlpDbCache = `-- name: GetYtDlpDbCache :one

SELECT url, audio_only, resolution, file_id, title, description, uploader, upload_count
FROM yt_dl_results
WHERE url = $1
  AND audio_only = $2
  AND resolution = $3
`

// encoding: utf-8
func (q *Queries) GetYtDlpDbCache(ctx context.Context, url string, audioOnly bool, resolution int32) (YtDlResult, error) {
	row := q.db.QueryRow(ctx, getYtDlpDbCache, url, audioOnly, resolution)
	var i YtDlResult
	err := row.Scan(
		&i.Url,
		&i.AudioOnly,
		&i.Resolution,
		&i.FileID,
		&i.Title,
		&i.Description,
		&i.Uploader,
		&i.UploadCount,
	)
	return i, err
}

const incYtDlUploadCount = `-- name: IncYtDlUploadCount :exec
UPDATE yt_dl_results
SET upload_count=upload_count + 1
WHERE file_id = $1
`

func (q *Queries) IncYtDlUploadCount(ctx context.Context, fileID string) error {
	_, err := q.db.Exec(ctx, incYtDlUploadCount, fileID)
	return err
}

const updateYtDlpCache = `-- name: UpdateYtDlpCache :exec
INSERT INTO yt_dl_results
(url, audio_only, resolution, file_id, title, description, uploader, upload_count)
VALUES ($1, $2, $3, $4, $5, $6, $7, 1)
ON CONFLICT (url, audio_only, resolution) DO UPDATE
    SET file_id=EXCLUDED.file_id,
        title=EXCLUDED.title,
        description=EXCLUDED.description,
        uploader=EXCLUDED.uploader
`

type UpdateYtDlpCacheParams struct {
	Url         string `json:"url"`
	AudioOnly   bool   `json:"audio_only"`
	Resolution  int32  `json:"resolution"`
	FileID      string `json:"file_id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	Uploader    string `json:"uploader"`
}

func (q *Queries) UpdateYtDlpCache(ctx context.Context, arg UpdateYtDlpCacheParams) error {
	_, err := q.db.Exec(ctx, updateYtDlpCache,
		arg.Url,
		arg.AudioOnly,
		arg.Resolution,
		arg.FileID,
		arg.Title,
		arg.Description,
		arg.Uploader,
	)
	return err
}
