// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query_bilibili.sql

package q

import (
	"context"
	"time"

	"go.uber.org/zap"
)

const createBiliInlineData = `-- name: CreateBiliInlineData :one
INSERT INTO bili_inline_results
    DEFAULT
VALUES
RETURNING uid
`

func (q *Queries) CreateBiliInlineData(ctx context.Context) (int64, error) {
	var logFields []zap.Field
	var start time.Time
	if q.logger != nil {
		logFields = make([]zap.Field, 0, 8)
		start = time.Now()
		if q.LogArgument {
			logFields = append(logFields, zap.Dict("fields"))
		}
	}
	row := q.queryRow(ctx, q.createBiliInlineDataStmt, createBiliInlineData)
	var uid int64
	err := row.Scan(&uid)
	q.logQuery(createBiliInlineData, "CreateBiliInlineData", logFields, err, start)
	return uid, err
}

const getBiliInlineData = `-- name: GetBiliInlineData :one

SELECT text, chat_id, msg_id
FROM bili_inline_results
WHERE uid = ?
`

type GetBiliInlineDataRow struct {
	Text   string `json:"text"`
	ChatID int64  `json:"chat_id"`
	MsgID  int64  `json:"msg_id"`
}

// encoding: utf-8
func (q *Queries) GetBiliInlineData(ctx context.Context, uid int64) (GetBiliInlineDataRow, error) {
	var logFields []zap.Field
	var start time.Time
	if q.logger != nil {
		logFields = make([]zap.Field, 0, 8)
		start = time.Now()
		if q.LogArgument {
			logFields = append(logFields,
				zap.Dict("fields",
					zap.Int64("uid", uid),
				),
			)
		}
	}
	row := q.queryRow(ctx, q.getBiliInlineDataStmt, getBiliInlineData, uid)
	var i GetBiliInlineDataRow
	err := row.Scan(&i.Text, &i.ChatID, &i.MsgID)
	q.logQuery(getBiliInlineData, "GetBiliInlineData", logFields, err, start)
	return i, err
}

const updateBiliInlineMsgId = `-- name: UpdateBiliInlineMsgId :exec
UPDATE bili_inline_results
SET text    = ?,
    chat_id = ?,
    msg_id  = ?
WHERE uid = ?
`

func (q *Queries) UpdateBiliInlineMsgId(ctx context.Context, text string, chatID int64, msgID int64, uid int64) error {
	var logFields []zap.Field
	var start time.Time
	if q.logger != nil {
		logFields = make([]zap.Field, 0, 8)
		start = time.Now()
		if q.LogArgument {
			logFields = append(logFields,
				zap.Dict("fields",
					zap.String("text", text),
					zap.Int64("chat_id", chatID),
					zap.Int64("msg_id", msgID),
					zap.Int64("uid", uid),
				),
			)
		}
	}
	_, err := q.exec(ctx, q.updateBiliInlineMsgIdStmt, updateBiliInlineMsgId,
		text,
		chatID,
		msgID,
		uid,
	)
	q.logQuery(updateBiliInlineMsgId, "UpdateBiliInlineMsgId", logFields, err, start)
	return err
}
