// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query_coc.sql

package q

import (
	"context"
)

const delCocCharAttr = `-- name: DelCocCharAttr :exec
DELETE
FROM character_attrs
WHERE user_id = $1
  AND attr_name = $2
`

func (q *Queries) DelCocCharAttr(ctx context.Context, userID int64, attrName string) error {
	_, err := q.db.Exec(ctx, delCocCharAttr, userID, attrName)
	return err
}

const getCocCharAllAttr = `-- name: GetCocCharAllAttr :many
SELECT attr_name, attr_value
FROM character_attrs
WHERE user_id = $1
`

type GetCocCharAllAttrRow struct {
	AttrName  string `json:"attr_name"`
	AttrValue string `json:"attr_value"`
}

func (q *Queries) GetCocCharAllAttr(ctx context.Context, userID int64) ([]GetCocCharAllAttrRow, error) {
	rows, err := q.db.Query(ctx, getCocCharAllAttr, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCocCharAllAttrRow
	for rows.Next() {
		var i GetCocCharAllAttrRow
		if err := rows.Scan(&i.AttrName, &i.AttrValue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCocCharAttr = `-- name: GetCocCharAttr :one

SELECT attr_value
FROM character_attrs
WHERE user_id = $1
  AND attr_name = $2
`

// encoding: utf-8
func (q *Queries) GetCocCharAttr(ctx context.Context, userID int64, attrName string) (string, error) {
	row := q.db.QueryRow(ctx, getCocCharAttr, userID, attrName)
	var attr_value string
	err := row.Scan(&attr_value)
	return attr_value, err
}

const setCocCharAttr = `-- name: SetCocCharAttr :exec
INSERT INTO character_attrs
    (user_id, attr_name, attr_value)
VALUES ($1, $2, $3)
ON CONFLICT DO UPDATE SET attr_value=excluded.attr_value
`

func (q *Queries) SetCocCharAttr(ctx context.Context, userID int64, attrName string, attrValue string) error {
	_, err := q.db.Exec(ctx, setCocCharAttr, userID, attrName, attrValue)
	return err
}
