openapi: 3.1.0
info:
  title: Bot HTTP Backend
  description: OpenAPI specification for the legacy bot HTTP endpoints.
  version: 1.0.0
servers:
  - url: http://127.0.0.1:4021

paths:
  /ping:
    get:
      tags:
        - Health
      summary: Ping the service
      description: Returns a simple JSON payload to verify the backend is running.
      responses:
        200:
          description: Service is reachable.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PingResponse'
  /tg/userinfo:
    post:
      tags:
        - Telegram
      summary: 使用Json同时获取多个用户的用户信息
      security:
        - TelegramAuth: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserQuery'
      responses:
        200:
          description: 用户列表
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        400:
          $ref: '#/components/responses/Error'
        401:
          $ref: '#/components/responses/Error'

  /tg/profile_photo/{filename}:
    get:
      tags:
        - Telegram
      summary: Get the user's profile photo in WEBP format
      parameters:
        - name: filename
          in: path
          required: true
          description: bot返回的文件名，应为bot api中获取的 file id + .webp。
          schema: { type: string }
      responses:
        200:
          description: Profile photo file.
          content:
            image/webp:
              schema:
                type: string
                format: binary
        400:
          $ref: '#/components/responses/Error'

  /tg/group_stat:
    get:
      tags:
        - Telegram
      summary: Get today's group statistics
      security:
        - TelegramAuth: [ ]
      parameters:
        - name: group_web_id
          in: query
          required: true
          description: Web id of the group, a random 64-bit integer.
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Group statistics for the current day.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatStat'
        400:
          $ref: '#/components/responses/Error'
        401:
          $ref: '#/components/responses/Error'

  /tg/search:
    post:
      tags:
        - Search
      summary: Search messages within a group
      security:
        - TelegramAuth: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchQuery'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/SearchQuery'
      responses:
        200:
          description: Search result list.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchResult'
        400:
          $ref: '#/components/responses/Error'
        401:
          $ref: '#/components/responses/Error'

components:
  responses:
    Error:
      description: 通用错误，以错误码区分具体遇到的是何种错误
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
  securitySchemes:
    TelegramAuth:
      type: apiKey
      in: header
      name: Authorization
      description: |
        Provide the Telegram WebApp `initData` in the Authorization header:
        `Authorization: Telegram <initData>`

  schemas:
    PingResponse:
      type: object
      properties:
        message:
          type: string
      required:
        - message

    ErrorResponse:
      type: object
      properties:
        status:
          type: string
          example: error
        code:
          type: integer
          format: int64
        error:
          type: string
      required:
        - status
        - code
        - error
    UserQuery:
      type: array
      items:
        type: integer
        format: int64

    User:
      type: object
      properties:
        user_id:
          type: integer
          format: int64
        first_name:
          type: string
        last_name:
          type: string
        username:
          type: string
        profile_photo:
          type: string
      required:
        - user_id
        - first_name

    UserMsgStat:
      type: object
      properties:
        MsgCount:
          type: integer
          format: int64
        MsgLen:
          type: integer
          format: int64
      required:
        - MsgCount
        - MsgLen

    UserMsgStatMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/UserMsgStat'

    TenMinuteStats:
      type: array
      description: 144 ten-minute buckets covering a full day.
      minItems: 144
      maxItems: 144
      items:
        type: integer
        format: int64

    ChatStat:
      type: object
      properties:
        chat_id:
          type: integer
          format: int64
        stat_date:
          type: integer
          format: int64
          description: UTC day represented as a Unix day number.
        message_count:
          type: integer
          format: int64
        photo_count:
          type: integer
          format: int64
        video_count:
          type: integer
          format: int64
        sticker_count:
          type: integer
          format: int64
        forward_count:
          type: integer
          format: int64
        mars_count:
          type: integer
          format: int64
        max_mars_count:
          type: integer
          format: int64
        racy_count:
          type: integer
          format: int64
        adult_count:
          type: integer
          format: int64
        download_video_count:
          type: integer
          format: int64
        download_audio_count:
          type: integer
          format: int64
        dio_add_user_count:
          type: integer
          format: int64
        dio_ban_user_count:
          type: integer
          format: int64
        user_msg_stat:
          $ref: '#/components/schemas/UserMsgStatMap'
        msg_count_by_time:
          $ref: '#/components/schemas/TenMinuteStats'
        msg_id_at_time_start:
          $ref: '#/components/schemas/TenMinuteStats'
      required:
        - chat_id
        - stat_date
        - message_count
        - photo_count
        - video_count
        - sticker_count
        - forward_count
        - mars_count
        - max_mars_count
        - racy_count
        - adult_count
        - download_video_count
        - download_audio_count
        - dio_add_user_count
        - dio_ban_user_count
        - user_msg_stat
        - msg_count_by_time
        - msg_id_at_time_start

    SearchQuery:
      type: object
      properties:
        q:
          type: string
          description: Search query string.
          minLength: 1
        ins_id:
          description: Group web id (Meilisearch index id).
          type: integer
          format: int64
        page:
          type: integer
          minimum: 1
        limit:
          type: integer
          minimum: 1
          maximum: 50
          default: 20
      required:
        - q
        - ins_id
        - page

    MeiliMsg:
      type: object
      properties:
        mongo_id:
          type: string
        peer_id:
          type: integer
          format: int64
        from_id:
          type: integer
          format: int64
        msg_id:
          type: integer
          format: int64
        date:
          type: number
          format: double
        message:
          type: string
        image_text:
          type: string
        qr_result:
          type: string

    SearchResult:
      type: object
      properties:
        hits:
          type: array
          items:
            $ref: '#/components/schemas/MeiliMsg'
        query:
          type: string
        processingTimeMs:
          type: integer
        limit:
          type: integer
        offset:
          type: integer
        estimatedTotalHits:
          type: integer
      required:
        - hits
        - query
        - processingTimeMs
        - limit
        - offset
        - estimatedTotalHits
