// Code generated by ogen, DO NOT EDIT.

package botapi

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// PingGet implements GET /ping operation.
	//
	// Returns a simple JSON payload to verify the backend is running.
	//
	// GET /ping
	PingGet(ctx context.Context) (*PingResponse, error)
	// TgGroupStatGet implements GET /tg/group_stat operation.
	//
	// Get today's group statistics.
	//
	// GET /tg/group_stat
	TgGroupStatGet(ctx context.Context, params TgGroupStatGetParams) (TgGroupStatGetRes, error)
	// TgProfilePhotoFilenameGet implements GET /tg/profile_photo/{filename} operation.
	//
	// Get the user's profile photo in WEBP format.
	//
	// GET /tg/profile_photo/{filename}
	TgProfilePhotoFilenameGet(ctx context.Context, params TgProfilePhotoFilenameGetParams) (TgProfilePhotoFilenameGetRes, error)
	// TgSearchPost implements POST /tg/search operation.
	//
	// Search messages within a group.
	//
	// POST /tg/search
	TgSearchPost(ctx context.Context, req TgSearchPostReq) (TgSearchPostRes, error)
	// TgUserinfoPost implements POST /tg/userinfo operation.
	//
	// 使用Json同时获取多个用户的用户信息.
	//
	// POST /tg/userinfo
	TgUserinfoPost(ctx context.Context, req UserQuery) (TgUserinfoPostRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
