// Code generated by ogen, DO NOT EDIT.
package botapi

type TgGroupStatGetRes interface {
	tgGroupStatGetRes()
}

type TgProfilePhotoFilenameGetRes interface {
	tgProfilePhotoFilenameGetRes()
}

type TgSearchPostReq interface {
	tgSearchPostReq()
}

type TgSearchPostRes interface {
	tgSearchPostRes()
}

type TgUserinfoPostRes interface {
	tgUserinfoPostRes()
}
