// Code generated by ogen, DO NOT EDIT.

package botapi

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// APIPingGet implements GET /api/ping operation.
	//
	// Returns a simple JSON payload to verify the backend is running.
	//
	// GET /api/ping
	APIPingGet(ctx context.Context) (*PingResponse, error)
	// APIV1TgGroupStatGet implements GET /api/v1/tg/group_stat operation.
	//
	// Get today's group statistics.
	//
	// GET /api/v1/tg/group_stat
	APIV1TgGroupStatGet(ctx context.Context, params APIV1TgGroupStatGetParams) (APIV1TgGroupStatGetRes, error)
	// APIV1TgProfilePhotoGet implements GET /api/v1/tg/profile_photo operation.
	//
	// Get the user's profile photo in WEBP format.
	//
	// GET /api/v1/tg/profile_photo
	APIV1TgProfilePhotoGet(ctx context.Context, params APIV1TgProfilePhotoGetParams) (APIV1TgProfilePhotoGetRes, error)
	// APIV1TgSearchGet implements GET /api/v1/tg/search operation.
	//
	// Search messages within a group.
	//
	// GET /api/v1/tg/search
	APIV1TgSearchGet(ctx context.Context, params APIV1TgSearchGetParams) (APIV1TgSearchGetRes, error)
	// APIV1TgSearchPost implements POST /api/v1/tg/search operation.
	//
	// Search messages within a group.
	//
	// POST /api/v1/tg/search
	APIV1TgSearchPost(ctx context.Context, req APIV1TgSearchPostReq) (APIV1TgSearchPostRes, error)
	// APIV1TgUsernameGet implements GET /api/v1/tg/username operation.
	//
	// Get a user name by Telegram user id.
	//
	// GET /api/v1/tg/username
	APIV1TgUsernameGet(ctx context.Context, params APIV1TgUsernameGetParams) (APIV1TgUsernameGetRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
