// Code generated by ogen, DO NOT EDIT.
package botapi

type TgGroupStatGetRes interface {
	tgGroupStatGetRes()
}

type TgProfilePhotoGetRes interface {
	tgProfilePhotoGetRes()
}

type TgSearchGetRes interface {
	tgSearchGetRes()
}

type TgSearchPostReq interface {
	tgSearchPostReq()
}

type TgSearchPostRes interface {
	tgSearchPostRes()
}

type TgUsernameGetRes interface {
	tgUsernameGetRes()
}
