// Code generated by ogen, DO NOT EDIT.

package botapi

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// TgGroupStatGetParams is parameters of GET /tg/group_stat operation.
type TgGroupStatGetParams struct {
	// Web id of the group, a random 64-bit integer.
	GroupWebID int64
}

func unpackTgGroupStatGetParams(packed middleware.Parameters) (params TgGroupStatGetParams) {
	{
		key := middleware.ParameterKey{
			Name: "group_web_id",
			In:   "query",
		}
		params.GroupWebID = packed[key].(int64)
	}
	return params
}

func decodeTgGroupStatGetParams(args [0]string, argsEscaped bool, r *http.Request) (params TgGroupStatGetParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: group_web_id.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "group_web_id",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt64(val)
				if err != nil {
					return err
				}

				params.GroupWebID = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "group_web_id",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// TgProfilePhotoFilenameGetParams is parameters of GET /tg/profile_photo/{filename} operation.
type TgProfilePhotoFilenameGetParams struct {
	// Bot返回的文件名，应为bot api中获取的 file id + .webp。.
	Filename string
	// Bot给出的sha256签名，使用该签名验证用户有权访问该图片，验证方式为
	// hmac(secret, filename) == sha256.
	SHA256 string
}

func unpackTgProfilePhotoFilenameGetParams(packed middleware.Parameters) (params TgProfilePhotoFilenameGetParams) {
	{
		key := middleware.ParameterKey{
			Name: "filename",
			In:   "path",
		}
		params.Filename = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "sha256",
			In:   "query",
		}
		params.SHA256 = packed[key].(string)
	}
	return params
}

func decodeTgProfilePhotoFilenameGetParams(args [1]string, argsEscaped bool, r *http.Request) (params TgProfilePhotoFilenameGetParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode path: filename.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "filename",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Filename = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "filename",
			In:   "path",
			Err:  err,
		}
	}
	// Decode query: sha256.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "sha256",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.SHA256 = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "sha256",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}
