// Code generated by ogen, DO NOT EDIT.

package botapi

import (
	"context"
	"net/http"
	"strings"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/ogenerrors"
)

// SecurityHandler is handler for security parameters.
type SecurityHandler interface {
	// HandleTelegramAuth handles TelegramAuth security.
	// Provide the Telegram WebApp `initData` in the Authorization header:
	// `Authorization: Telegram <initData>`.
	HandleTelegramAuth(ctx context.Context, operationName OperationName, t TelegramAuth) (context.Context, error)
}

func findAuthorization(h http.Header, prefix string) (string, bool) {
	v, ok := h["Authorization"]
	if !ok {
		return "", false
	}
	for _, vv := range v {
		scheme, value, ok := strings.Cut(vv, " ")
		if !ok || !strings.EqualFold(scheme, prefix) {
			continue
		}
		return value, true
	}
	return "", false
}

var operationRolesTelegramAuth = map[string][]string{
	TgGroupStatGetOperation: []string{},
	TgSearchGetOperation:    []string{},
	TgSearchPostOperation:   []string{},
}

func (s *Server) securityTelegramAuth(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t TelegramAuth
	const parameterName = "Authorization"
	value := req.Header.Get(parameterName)
	if value == "" {
		return ctx, false, nil
	}
	t.APIKey = value
	t.Roles = operationRolesTelegramAuth[operationName]
	rctx, err := s.sec.HandleTelegramAuth(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}
