// Code generated by ogen, DO NOT EDIT.

package botapi

// OperationName is the ogen operation name
type OperationName = string

const (
	APIPingGetOperation             OperationName = "APIPingGet"
	APIV1TgGroupStatGetOperation    OperationName = "APIV1TgGroupStatGet"
	APIV1TgProfilePhotoGetOperation OperationName = "APIV1TgProfilePhotoGet"
	APIV1TgSearchGetOperation       OperationName = "APIV1TgSearchGet"
	APIV1TgSearchPostOperation      OperationName = "APIV1TgSearchPost"
	APIV1TgUsernameGetOperation     OperationName = "APIV1TgUsernameGet"
)
