// Code generated by ogen, DO NOT EDIT.

package botapi

import (
	"io"
)

// Ref: #/components/schemas/ChatStat
type ChatStat struct {
	ChatID int64 `json:"chat_id"`
	// UTC day represented as a Unix day number.
	StatDate           int64          `json:"stat_date"`
	MessageCount       int64          `json:"message_count"`
	PhotoCount         int64          `json:"photo_count"`
	VideoCount         int64          `json:"video_count"`
	StickerCount       int64          `json:"sticker_count"`
	ForwardCount       int64          `json:"forward_count"`
	MarsCount          int64          `json:"mars_count"`
	MaxMarsCount       int64          `json:"max_mars_count"`
	RacyCount          int64          `json:"racy_count"`
	AdultCount         int64          `json:"adult_count"`
	DownloadVideoCount int64          `json:"download_video_count"`
	DownloadAudioCount int64          `json:"download_audio_count"`
	DioAddUserCount    int64          `json:"dio_add_user_count"`
	DioBanUserCount    int64          `json:"dio_ban_user_count"`
	UserMsgStat        UserMsgStatMap `json:"user_msg_stat"`
	MsgCountByTime     TenMinuteStats `json:"msg_count_by_time"`
	MsgIDAtTimeStart   TenMinuteStats `json:"msg_id_at_time_start"`
}

// GetChatID returns the value of ChatID.
func (s *ChatStat) GetChatID() int64 {
	return s.ChatID
}

// GetStatDate returns the value of StatDate.
func (s *ChatStat) GetStatDate() int64 {
	return s.StatDate
}

// GetMessageCount returns the value of MessageCount.
func (s *ChatStat) GetMessageCount() int64 {
	return s.MessageCount
}

// GetPhotoCount returns the value of PhotoCount.
func (s *ChatStat) GetPhotoCount() int64 {
	return s.PhotoCount
}

// GetVideoCount returns the value of VideoCount.
func (s *ChatStat) GetVideoCount() int64 {
	return s.VideoCount
}

// GetStickerCount returns the value of StickerCount.
func (s *ChatStat) GetStickerCount() int64 {
	return s.StickerCount
}

// GetForwardCount returns the value of ForwardCount.
func (s *ChatStat) GetForwardCount() int64 {
	return s.ForwardCount
}

// GetMarsCount returns the value of MarsCount.
func (s *ChatStat) GetMarsCount() int64 {
	return s.MarsCount
}

// GetMaxMarsCount returns the value of MaxMarsCount.
func (s *ChatStat) GetMaxMarsCount() int64 {
	return s.MaxMarsCount
}

// GetRacyCount returns the value of RacyCount.
func (s *ChatStat) GetRacyCount() int64 {
	return s.RacyCount
}

// GetAdultCount returns the value of AdultCount.
func (s *ChatStat) GetAdultCount() int64 {
	return s.AdultCount
}

// GetDownloadVideoCount returns the value of DownloadVideoCount.
func (s *ChatStat) GetDownloadVideoCount() int64 {
	return s.DownloadVideoCount
}

// GetDownloadAudioCount returns the value of DownloadAudioCount.
func (s *ChatStat) GetDownloadAudioCount() int64 {
	return s.DownloadAudioCount
}

// GetDioAddUserCount returns the value of DioAddUserCount.
func (s *ChatStat) GetDioAddUserCount() int64 {
	return s.DioAddUserCount
}

// GetDioBanUserCount returns the value of DioBanUserCount.
func (s *ChatStat) GetDioBanUserCount() int64 {
	return s.DioBanUserCount
}

// GetUserMsgStat returns the value of UserMsgStat.
func (s *ChatStat) GetUserMsgStat() UserMsgStatMap {
	return s.UserMsgStat
}

// GetMsgCountByTime returns the value of MsgCountByTime.
func (s *ChatStat) GetMsgCountByTime() TenMinuteStats {
	return s.MsgCountByTime
}

// GetMsgIDAtTimeStart returns the value of MsgIDAtTimeStart.
func (s *ChatStat) GetMsgIDAtTimeStart() TenMinuteStats {
	return s.MsgIDAtTimeStart
}

// SetChatID sets the value of ChatID.
func (s *ChatStat) SetChatID(val int64) {
	s.ChatID = val
}

// SetStatDate sets the value of StatDate.
func (s *ChatStat) SetStatDate(val int64) {
	s.StatDate = val
}

// SetMessageCount sets the value of MessageCount.
func (s *ChatStat) SetMessageCount(val int64) {
	s.MessageCount = val
}

// SetPhotoCount sets the value of PhotoCount.
func (s *ChatStat) SetPhotoCount(val int64) {
	s.PhotoCount = val
}

// SetVideoCount sets the value of VideoCount.
func (s *ChatStat) SetVideoCount(val int64) {
	s.VideoCount = val
}

// SetStickerCount sets the value of StickerCount.
func (s *ChatStat) SetStickerCount(val int64) {
	s.StickerCount = val
}

// SetForwardCount sets the value of ForwardCount.
func (s *ChatStat) SetForwardCount(val int64) {
	s.ForwardCount = val
}

// SetMarsCount sets the value of MarsCount.
func (s *ChatStat) SetMarsCount(val int64) {
	s.MarsCount = val
}

// SetMaxMarsCount sets the value of MaxMarsCount.
func (s *ChatStat) SetMaxMarsCount(val int64) {
	s.MaxMarsCount = val
}

// SetRacyCount sets the value of RacyCount.
func (s *ChatStat) SetRacyCount(val int64) {
	s.RacyCount = val
}

// SetAdultCount sets the value of AdultCount.
func (s *ChatStat) SetAdultCount(val int64) {
	s.AdultCount = val
}

// SetDownloadVideoCount sets the value of DownloadVideoCount.
func (s *ChatStat) SetDownloadVideoCount(val int64) {
	s.DownloadVideoCount = val
}

// SetDownloadAudioCount sets the value of DownloadAudioCount.
func (s *ChatStat) SetDownloadAudioCount(val int64) {
	s.DownloadAudioCount = val
}

// SetDioAddUserCount sets the value of DioAddUserCount.
func (s *ChatStat) SetDioAddUserCount(val int64) {
	s.DioAddUserCount = val
}

// SetDioBanUserCount sets the value of DioBanUserCount.
func (s *ChatStat) SetDioBanUserCount(val int64) {
	s.DioBanUserCount = val
}

// SetUserMsgStat sets the value of UserMsgStat.
func (s *ChatStat) SetUserMsgStat(val UserMsgStatMap) {
	s.UserMsgStat = val
}

// SetMsgCountByTime sets the value of MsgCountByTime.
func (s *ChatStat) SetMsgCountByTime(val TenMinuteStats) {
	s.MsgCountByTime = val
}

// SetMsgIDAtTimeStart sets the value of MsgIDAtTimeStart.
func (s *ChatStat) SetMsgIDAtTimeStart(val TenMinuteStats) {
	s.MsgIDAtTimeStart = val
}

func (*ChatStat) tgGroupStatGetRes() {}

// Ref: #/components/schemas/ErrorResponse
type ErrorResponse struct {
	Status string `json:"status"`
	Code   int64  `json:"code"`
	Error  string `json:"error"`
}

// GetStatus returns the value of Status.
func (s *ErrorResponse) GetStatus() string {
	return s.Status
}

// GetCode returns the value of Code.
func (s *ErrorResponse) GetCode() int64 {
	return s.Code
}

// GetError returns the value of Error.
func (s *ErrorResponse) GetError() string {
	return s.Error
}

// SetStatus sets the value of Status.
func (s *ErrorResponse) SetStatus(val string) {
	s.Status = val
}

// SetCode sets the value of Code.
func (s *ErrorResponse) SetCode(val int64) {
	s.Code = val
}

// SetError sets the value of Error.
func (s *ErrorResponse) SetError(val string) {
	s.Error = val
}

func (*ErrorResponse) tgProfilePhotoGetRes() {}
func (*ErrorResponse) tgUsernameGetRes()     {}

// Ref: #/components/schemas/MeiliMsg
type MeiliMsg struct {
	MongoID   OptString  `json:"mongo_id"`
	PeerID    OptInt64   `json:"peer_id"`
	FromID    OptInt64   `json:"from_id"`
	MsgID     OptInt64   `json:"msg_id"`
	Date      OptFloat64 `json:"date"`
	Message   OptString  `json:"message"`
	ImageText OptString  `json:"image_text"`
	QrResult  OptString  `json:"qr_result"`
}

// GetMongoID returns the value of MongoID.
func (s *MeiliMsg) GetMongoID() OptString {
	return s.MongoID
}

// GetPeerID returns the value of PeerID.
func (s *MeiliMsg) GetPeerID() OptInt64 {
	return s.PeerID
}

// GetFromID returns the value of FromID.
func (s *MeiliMsg) GetFromID() OptInt64 {
	return s.FromID
}

// GetMsgID returns the value of MsgID.
func (s *MeiliMsg) GetMsgID() OptInt64 {
	return s.MsgID
}

// GetDate returns the value of Date.
func (s *MeiliMsg) GetDate() OptFloat64 {
	return s.Date
}

// GetMessage returns the value of Message.
func (s *MeiliMsg) GetMessage() OptString {
	return s.Message
}

// GetImageText returns the value of ImageText.
func (s *MeiliMsg) GetImageText() OptString {
	return s.ImageText
}

// GetQrResult returns the value of QrResult.
func (s *MeiliMsg) GetQrResult() OptString {
	return s.QrResult
}

// SetMongoID sets the value of MongoID.
func (s *MeiliMsg) SetMongoID(val OptString) {
	s.MongoID = val
}

// SetPeerID sets the value of PeerID.
func (s *MeiliMsg) SetPeerID(val OptInt64) {
	s.PeerID = val
}

// SetFromID sets the value of FromID.
func (s *MeiliMsg) SetFromID(val OptInt64) {
	s.FromID = val
}

// SetMsgID sets the value of MsgID.
func (s *MeiliMsg) SetMsgID(val OptInt64) {
	s.MsgID = val
}

// SetDate sets the value of Date.
func (s *MeiliMsg) SetDate(val OptFloat64) {
	s.Date = val
}

// SetMessage sets the value of Message.
func (s *MeiliMsg) SetMessage(val OptString) {
	s.Message = val
}

// SetImageText sets the value of ImageText.
func (s *MeiliMsg) SetImageText(val OptString) {
	s.ImageText = val
}

// SetQrResult sets the value of QrResult.
func (s *MeiliMsg) SetQrResult(val OptString) {
	s.QrResult = val
}

// NewOptFloat64 returns new OptFloat64 with value set to v.
func NewOptFloat64(v float64) OptFloat64 {
	return OptFloat64{
		Value: v,
		Set:   true,
	}
}

// OptFloat64 is optional float64.
type OptFloat64 struct {
	Value float64
	Set   bool
}

// IsSet returns true if OptFloat64 was set.
func (o OptFloat64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptFloat64) Reset() {
	var v float64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptFloat64) SetTo(v float64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptFloat64) Get() (v float64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptFloat64) Or(d float64) float64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt64 returns new OptInt64 with value set to v.
func NewOptInt64(v int64) OptInt64 {
	return OptInt64{
		Value: v,
		Set:   true,
	}
}

// OptInt64 is optional int64.
type OptInt64 struct {
	Value int64
	Set   bool
}

// IsSet returns true if OptInt64 was set.
func (o OptInt64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt64) Reset() {
	var v int64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt64) SetTo(v int64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt64) Get() (v int64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt64) Or(d int64) int64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/PingResponse
type PingResponse struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *PingResponse) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *PingResponse) SetMessage(val string) {
	s.Message = val
}

// Ref: #/components/schemas/SearchQuery
type SearchQuery struct {
	// Search query string.
	Q string `json:"q"`
	// Group web id (Meilisearch index id).
	InsID int64  `json:"ins_id"`
	Page  int    `json:"page"`
	Limit OptInt `json:"limit"`
}

// GetQ returns the value of Q.
func (s *SearchQuery) GetQ() string {
	return s.Q
}

// GetInsID returns the value of InsID.
func (s *SearchQuery) GetInsID() int64 {
	return s.InsID
}

// GetPage returns the value of Page.
func (s *SearchQuery) GetPage() int {
	return s.Page
}

// GetLimit returns the value of Limit.
func (s *SearchQuery) GetLimit() OptInt {
	return s.Limit
}

// SetQ sets the value of Q.
func (s *SearchQuery) SetQ(val string) {
	s.Q = val
}

// SetInsID sets the value of InsID.
func (s *SearchQuery) SetInsID(val int64) {
	s.InsID = val
}

// SetPage sets the value of Page.
func (s *SearchQuery) SetPage(val int) {
	s.Page = val
}

// SetLimit sets the value of Limit.
func (s *SearchQuery) SetLimit(val OptInt) {
	s.Limit = val
}

// Ref: #/components/schemas/SearchResult
type SearchResult struct {
	Hits               []MeiliMsg `json:"hits"`
	Query              string     `json:"query"`
	ProcessingTimeMs   int        `json:"processingTimeMs"`
	Limit              int        `json:"limit"`
	Offset             int        `json:"offset"`
	EstimatedTotalHits int        `json:"estimatedTotalHits"`
}

// GetHits returns the value of Hits.
func (s *SearchResult) GetHits() []MeiliMsg {
	return s.Hits
}

// GetQuery returns the value of Query.
func (s *SearchResult) GetQuery() string {
	return s.Query
}

// GetProcessingTimeMs returns the value of ProcessingTimeMs.
func (s *SearchResult) GetProcessingTimeMs() int {
	return s.ProcessingTimeMs
}

// GetLimit returns the value of Limit.
func (s *SearchResult) GetLimit() int {
	return s.Limit
}

// GetOffset returns the value of Offset.
func (s *SearchResult) GetOffset() int {
	return s.Offset
}

// GetEstimatedTotalHits returns the value of EstimatedTotalHits.
func (s *SearchResult) GetEstimatedTotalHits() int {
	return s.EstimatedTotalHits
}

// SetHits sets the value of Hits.
func (s *SearchResult) SetHits(val []MeiliMsg) {
	s.Hits = val
}

// SetQuery sets the value of Query.
func (s *SearchResult) SetQuery(val string) {
	s.Query = val
}

// SetProcessingTimeMs sets the value of ProcessingTimeMs.
func (s *SearchResult) SetProcessingTimeMs(val int) {
	s.ProcessingTimeMs = val
}

// SetLimit sets the value of Limit.
func (s *SearchResult) SetLimit(val int) {
	s.Limit = val
}

// SetOffset sets the value of Offset.
func (s *SearchResult) SetOffset(val int) {
	s.Offset = val
}

// SetEstimatedTotalHits sets the value of EstimatedTotalHits.
func (s *SearchResult) SetEstimatedTotalHits(val int) {
	s.EstimatedTotalHits = val
}

func (*SearchResult) tgSearchGetRes()  {}
func (*SearchResult) tgSearchPostRes() {}

type TelegramAuth struct {
	APIKey string
	Roles  []string
}

// GetAPIKey returns the value of APIKey.
func (s *TelegramAuth) GetAPIKey() string {
	return s.APIKey
}

// GetRoles returns the value of Roles.
func (s *TelegramAuth) GetRoles() []string {
	return s.Roles
}

// SetAPIKey sets the value of APIKey.
func (s *TelegramAuth) SetAPIKey(val string) {
	s.APIKey = val
}

// SetRoles sets the value of Roles.
func (s *TelegramAuth) SetRoles(val []string) {
	s.Roles = val
}

type TenMinuteStats []int64

type TgGroupStatGetBadRequest ErrorResponse

func (*TgGroupStatGetBadRequest) tgGroupStatGetRes() {}

type TgGroupStatGetUnauthorized ErrorResponse

func (*TgGroupStatGetUnauthorized) tgGroupStatGetRes() {}

type TgProfilePhotoGetOK struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s TgProfilePhotoGetOK) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*TgProfilePhotoGetOK) tgProfilePhotoGetRes() {}

type TgSearchGetBadRequest ErrorResponse

func (*TgSearchGetBadRequest) tgSearchGetRes() {}

type TgSearchGetUnauthorized ErrorResponse

func (*TgSearchGetUnauthorized) tgSearchGetRes() {}

type TgSearchPostApplicationJSON SearchQuery

func (*TgSearchPostApplicationJSON) tgSearchPostReq() {}

type TgSearchPostApplicationXWwwFormUrlencoded SearchQuery

func (*TgSearchPostApplicationXWwwFormUrlencoded) tgSearchPostReq() {}

type TgSearchPostBadRequest ErrorResponse

func (*TgSearchPostBadRequest) tgSearchPostRes() {}

type TgSearchPostUnauthorized ErrorResponse

func (*TgSearchPostUnauthorized) tgSearchPostRes() {}

// Ref: #/components/schemas/User
type User struct {
	UserID int64  `json:"user_id"`
	Name   string `json:"name"`
}

// GetUserID returns the value of UserID.
func (s *User) GetUserID() int64 {
	return s.UserID
}

// GetName returns the value of Name.
func (s *User) GetName() string {
	return s.Name
}

// SetUserID sets the value of UserID.
func (s *User) SetUserID(val int64) {
	s.UserID = val
}

// SetName sets the value of Name.
func (s *User) SetName(val string) {
	s.Name = val
}

func (*User) tgUsernameGetRes() {}

// Ref: #/components/schemas/UserMsgStat
type UserMsgStat struct {
	MsgCount int64 `json:"MsgCount"`
	MsgLen   int64 `json:"MsgLen"`
}

// GetMsgCount returns the value of MsgCount.
func (s *UserMsgStat) GetMsgCount() int64 {
	return s.MsgCount
}

// GetMsgLen returns the value of MsgLen.
func (s *UserMsgStat) GetMsgLen() int64 {
	return s.MsgLen
}

// SetMsgCount sets the value of MsgCount.
func (s *UserMsgStat) SetMsgCount(val int64) {
	s.MsgCount = val
}

// SetMsgLen sets the value of MsgLen.
func (s *UserMsgStat) SetMsgLen(val int64) {
	s.MsgLen = val
}

// Ref: #/components/schemas/UserMsgStatMap
type UserMsgStatMap map[string]UserMsgStat

func (s *UserMsgStatMap) init() UserMsgStatMap {
	m := *s
	if m == nil {
		m = map[string]UserMsgStat{}
		*s = m
	}
	return m
}
