// Code generated by ogen, DO NOT EDIT.

package botapi

// OperationName is the ogen operation name
type OperationName = string

const (
	PingGetOperation                   OperationName = "PingGet"
	TgGroupStatGetOperation            OperationName = "TgGroupStatGet"
	TgProfilePhotoFilenameGetOperation OperationName = "TgProfilePhotoFilenameGet"
	TgSearchPostOperation              OperationName = "TgSearchPost"
	TgUserinfoPostOperation            OperationName = "TgUserinfoPost"
)
