// Code generated by ogen, DO NOT EDIT.

package botapi

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// PingGet implements GET /ping operation.
	//
	// Returns a simple JSON payload to verify the backend is running.
	//
	// GET /ping
	PingGet(ctx context.Context) (*PingResponse, error)
	// TgGroupStatGet implements GET /tg/group_stat operation.
	//
	// Get today's group statistics.
	//
	// GET /tg/group_stat
	TgGroupStatGet(ctx context.Context, params TgGroupStatGetParams) (TgGroupStatGetRes, error)
	// TgProfilePhotoGet implements GET /tg/profile_photo operation.
	//
	// Get the user's profile photo in WEBP format.
	//
	// GET /tg/profile_photo
	TgProfilePhotoGet(ctx context.Context, params TgProfilePhotoGetParams) (TgProfilePhotoGetRes, error)
	// TgSearchGet implements GET /tg/search operation.
	//
	// Search messages within a group.
	//
	// GET /tg/search
	TgSearchGet(ctx context.Context, params TgSearchGetParams) (TgSearchGetRes, error)
	// TgSearchPost implements POST /tg/search operation.
	//
	// Search messages within a group.
	//
	// POST /tg/search
	TgSearchPost(ctx context.Context, req TgSearchPostReq) (TgSearchPostRes, error)
	// TgUsernameGet implements GET /tg/username operation.
	//
	// Get a user name by Telegram user id.
	//
	// GET /tg/username
	TgUsernameGet(ctx context.Context, params TgUsernameGetParams) (TgUsernameGetRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
