// Code generated by ogen, DO NOT EDIT.
package botapi

type APIV1TgGroupStatGetRes interface {
	aPIV1TgGroupStatGetRes()
}

type APIV1TgProfilePhotoGetRes interface {
	aPIV1TgProfilePhotoGetRes()
}

type APIV1TgSearchGetRes interface {
	aPIV1TgSearchGetRes()
}

type APIV1TgSearchPostReq interface {
	aPIV1TgSearchPostReq()
}

type APIV1TgSearchPostRes interface {
	aPIV1TgSearchPostRes()
}

type APIV1TgUsernameGetRes interface {
	aPIV1TgUsernameGetRes()
}
