bot-token: "***REMOVED***"

god: 199456161
my-chats:
  - -1001471592463
  - -1001126241898
  - -1001170816274

mongo-url: ***REMOVED***

content-moderator:
  endpoint: "https://sese-detect.cognitiveservices.azure.com"
  api-key: "***REMOVED***"
ocr:
  endpoint: "https://bot-cv.cognitiveservices.azure.com"
  api-key: '***REMOVED***'
  api-ver: "2023-02-01-preview"
  language: ""
  features: "Read"

qr-scan-url: ***REMOVED***
save-message: true
tg-api-url: ***REMOVED***
drop-pending-updates: false

meili-config:
  base-url: ***REMOVED***
  index-name: tgmsgs
  primary-key: mongo_id
  master-key:

sese:
  adult-threshold: 0.8
  racy-threshold: 0.6

log-level: -1
local-kv-db-path: ./caches.badb