/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ping the service
         * @description Returns a simple JSON payload to verify the backend is running.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service is reachable. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PingResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tg/userinfo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 使用Json同时获取多个用户的用户信息 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UserQuery"];
                };
            };
            responses: {
                /** @description 用户列表 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                400: components["responses"]["Error"];
                401: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tg/profile_photo/{filename}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the user's profile photo in WEBP format */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description bot返回的文件名，应为bot api中获取的 file id + .webp。 */
                    filename: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Profile photo file. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "image/webp": string;
                    };
                };
                400: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tg/group_stat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get today's group statistics */
        get: {
            parameters: {
                query: {
                    /** @description Web id of the group, a random 64-bit integer. */
                    group_web_id: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Group statistics for the current day. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChatStat"];
                    };
                };
                400: components["responses"]["Error"];
                401: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tg/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search messages within a group */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SearchQuery"];
                    "application/x-www-form-urlencoded": components["schemas"]["SearchQuery"];
                };
            };
            responses: {
                /** @description Search result list. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SearchResult"];
                    };
                };
                400: components["responses"]["Error"];
                401: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        PingResponse: {
            message: string;
        };
        ErrorResponse: {
            /** @example error */
            status: string;
            /** Format: int64 */
            code: number;
            error: string;
        };
        UserQuery: number[];
        User: {
            /** Format: int64 */
            user_id: number;
            first_name: string;
            last_name?: string;
            username?: string;
            profile_photo?: string;
        };
        UserMsgStat: {
            /** Format: int64 */
            MsgCount: number;
            /** Format: int64 */
            MsgLen: number;
        };
        UserMsgStatMap: {
            [key: string]: components["schemas"]["UserMsgStat"];
        };
        /** @description 144 ten-minute buckets covering a full day. */
        TenMinuteStats: number[];
        ChatStat: {
            /** Format: int64 */
            chat_id: number;
            /**
             * Format: int64
             * @description UTC day represented as a Unix day number.
             */
            stat_date: number;
            /** Format: int64 */
            message_count: number;
            /** Format: int64 */
            photo_count: number;
            /** Format: int64 */
            video_count: number;
            /** Format: int64 */
            sticker_count: number;
            /** Format: int64 */
            forward_count: number;
            /** Format: int64 */
            mars_count: number;
            /** Format: int64 */
            max_mars_count: number;
            /** Format: int64 */
            racy_count: number;
            /** Format: int64 */
            adult_count: number;
            /** Format: int64 */
            download_video_count: number;
            /** Format: int64 */
            download_audio_count: number;
            /** Format: int64 */
            dio_add_user_count: number;
            /** Format: int64 */
            dio_ban_user_count: number;
            user_msg_stat: components["schemas"]["UserMsgStatMap"];
            msg_count_by_time: components["schemas"]["TenMinuteStats"];
            msg_id_at_time_start: components["schemas"]["TenMinuteStats"];
        };
        SearchQuery: {
            /** @description Search query string. */
            q: string;
            /**
             * Format: int64
             * @description Group web id (Meilisearch index id).
             */
            ins_id: number;
            page: number;
            /** @default 20 */
            limit: number;
        };
        MeiliMsg: {
            mongo_id?: string;
            /** Format: int64 */
            peer_id?: number;
            /** Format: int64 */
            from_id?: number;
            /** Format: int64 */
            msg_id?: number;
            /** Format: double */
            date?: number;
            message?: string;
            image_text?: string;
            qr_result?: string;
        };
        SearchResult: {
            hits: components["schemas"]["MeiliMsg"][];
            query: string;
            processingTimeMs: number;
            limit: number;
            offset: number;
            estimatedTotalHits: number;
        };
    };
    responses: {
        /** @description 通用错误，以错误码区分具体遇到的是何种错误 */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
