// Code generated by ogen, DO NOT EDIT.

package ogen

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// GetUserAvatar implements getUserAvatar operation.
	//
	// Get a user's avatar (webp).
	//
	// GET /users/{userId}/avatar
	GetUserAvatar(ctx context.Context, params GetUserAvatarParams) (GetUserAvatarRes, error)
	// GetUsersInfo implements getUsersInfo operation.
	//
	// Get basic info for multiple users.
	//
	// POST /users/info
	GetUsersInfo(ctx context.Context, req *UserInfoRequest) (GetUsersInfoRes, error)
	// SearchMessages implements searchMessages operation.
	//
	// Search messages for a group.
	//
	// POST /search
	SearchMessages(ctx context.Context, req *SearchRequest) (SearchMessagesRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
