// Code generated by ogen, DO NOT EDIT.

package ogen

import (
	"context"
	"net/http"
	"strings"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/ogenerrors"
)

// SecurityHandler is handler for security parameters.
type SecurityHandler interface {
	// HandleTgAuth handles TgAuth security.
	HandleTgAuth(ctx context.Context, operationName OperationName, t TgAuth) (context.Context, error)
}

func findAuthorization(h http.Header, prefix string) (string, bool) {
	v, ok := h["Authorization"]
	if !ok {
		return "", false
	}
	for _, vv := range v {
		scheme, value, ok := strings.Cut(vv, " ")
		if !ok || !strings.EqualFold(scheme, prefix) {
			continue
		}
		return value, true
	}
	return "", false
}

var operationRolesTgAuth = map[string][]string{
	GetUsersInfoOperation:   []string{},
	SearchMessagesOperation: []string{},
}

func (s *Server) securityTgAuth(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t TgAuth
	const parameterName = "X-Telegram-Init-Data"
	value := req.Header.Get(parameterName)
	if value == "" {
		return ctx, false, nil
	}
	t.APIKey = value
	t.Roles = operationRolesTgAuth[operationName]
	rctx, err := s.sec.HandleTgAuth(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// TgAuth provides TgAuth security value.
	TgAuth(ctx context.Context, operationName OperationName) (TgAuth, error)
}

func (s *Client) securityTgAuth(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.TgAuth(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"TgAuth\"")
	}
	req.Header.Set("X-Telegram-Init-Data", t.APIKey)
	return nil
}
