// Code generated by ogen, DO NOT EDIT.
package ogen

type GetUserAvatarRes interface {
	getUserAvatarRes()
}

type GetUsersInfoRes interface {
	getUsersInfoRes()
}

type SearchMessagesRes interface {
	searchMessagesRes()
}
