// Code generated by ogen, DO NOT EDIT.

package ogen

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetUserAvatar implements getUserAvatar operation.
//
// Get a user's avatar (webp).
//
// GET /users/{userId}/avatar
func (UnimplementedHandler) GetUserAvatar(ctx context.Context, params GetUserAvatarParams) (r GetUserAvatarRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUsersInfo implements getUsersInfo operation.
//
// Get basic info for multiple users.
//
// POST /users/info
func (UnimplementedHandler) GetUsersInfo(ctx context.Context, req *UserInfoRequest) (r GetUsersInfoRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SearchMessages implements searchMessages operation.
//
// Search messages for a group.
//
// POST /search
func (UnimplementedHandler) SearchMessages(ctx context.Context, req *SearchRequest) (r SearchMessagesRes, _ error) {
	return r, ht.ErrNotImplemented
}
