// Code generated by ogen, DO NOT EDIT.

package ogen

// setDefaults set default value of fields.
func (s *SearchRequest) setDefaults() {
	{
		val := int32(1)
		s.Page = val
	}
	{
		val := int32(20)
		s.Limit.SetTo(val)
	}
}
