// Code generated by ogen, DO NOT EDIT.

package ogen

import (
	"io"
)

// Ref: #/components/schemas/Error
type Error struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *Error) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *Error) SetMessage(val string) {
	s.Message = val
}

type GetUserAvatarForbidden Error

func (*GetUserAvatarForbidden) getUserAvatarRes() {}

type GetUserAvatarInternalServerError Error

func (*GetUserAvatarInternalServerError) getUserAvatarRes() {}

type GetUserAvatarNotFound Error

func (*GetUserAvatarNotFound) getUserAvatarRes() {}

type GetUserAvatarOK struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetUserAvatarOK) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetUserAvatarOK) getUserAvatarRes() {}

type GetUserAvatarUnauthorized Error

func (*GetUserAvatarUnauthorized) getUserAvatarRes() {}

type GetUsersInfoBadRequest Error

func (*GetUsersInfoBadRequest) getUsersInfoRes() {}

type GetUsersInfoInternalServerError Error

func (*GetUsersInfoInternalServerError) getUsersInfoRes() {}

// Ref: #/components/schemas/MeiliMsg
type MeiliMsg struct {
	MongoID   OptString  `json:"mongo_id"`
	PeerID    OptInt64   `json:"peer_id"`
	FromID    OptInt64   `json:"from_id"`
	MsgID     OptInt64   `json:"msg_id"`
	Date      OptFloat64 `json:"date"`
	Message   OptString  `json:"message"`
	ImageText OptString  `json:"image_text"`
	QrResult  OptString  `json:"qr_result"`
}

// GetMongoID returns the value of MongoID.
func (s *MeiliMsg) GetMongoID() OptString {
	return s.MongoID
}

// GetPeerID returns the value of PeerID.
func (s *MeiliMsg) GetPeerID() OptInt64 {
	return s.PeerID
}

// GetFromID returns the value of FromID.
func (s *MeiliMsg) GetFromID() OptInt64 {
	return s.FromID
}

// GetMsgID returns the value of MsgID.
func (s *MeiliMsg) GetMsgID() OptInt64 {
	return s.MsgID
}

// GetDate returns the value of Date.
func (s *MeiliMsg) GetDate() OptFloat64 {
	return s.Date
}

// GetMessage returns the value of Message.
func (s *MeiliMsg) GetMessage() OptString {
	return s.Message
}

// GetImageText returns the value of ImageText.
func (s *MeiliMsg) GetImageText() OptString {
	return s.ImageText
}

// GetQrResult returns the value of QrResult.
func (s *MeiliMsg) GetQrResult() OptString {
	return s.QrResult
}

// SetMongoID sets the value of MongoID.
func (s *MeiliMsg) SetMongoID(val OptString) {
	s.MongoID = val
}

// SetPeerID sets the value of PeerID.
func (s *MeiliMsg) SetPeerID(val OptInt64) {
	s.PeerID = val
}

// SetFromID sets the value of FromID.
func (s *MeiliMsg) SetFromID(val OptInt64) {
	s.FromID = val
}

// SetMsgID sets the value of MsgID.
func (s *MeiliMsg) SetMsgID(val OptInt64) {
	s.MsgID = val
}

// SetDate sets the value of Date.
func (s *MeiliMsg) SetDate(val OptFloat64) {
	s.Date = val
}

// SetMessage sets the value of Message.
func (s *MeiliMsg) SetMessage(val OptString) {
	s.Message = val
}

// SetImageText sets the value of ImageText.
func (s *MeiliMsg) SetImageText(val OptString) {
	s.ImageText = val
}

// SetQrResult sets the value of QrResult.
func (s *MeiliMsg) SetQrResult(val OptString) {
	s.QrResult = val
}

// NewOptFloat64 returns new OptFloat64 with value set to v.
func NewOptFloat64(v float64) OptFloat64 {
	return OptFloat64{
		Value: v,
		Set:   true,
	}
}

// OptFloat64 is optional float64.
type OptFloat64 struct {
	Value float64
	Set   bool
}

// IsSet returns true if OptFloat64 was set.
func (o OptFloat64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptFloat64) Reset() {
	var v float64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptFloat64) SetTo(v float64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptFloat64) Get() (v float64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptFloat64) Or(d float64) float64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt32 returns new OptInt32 with value set to v.
func NewOptInt32(v int32) OptInt32 {
	return OptInt32{
		Value: v,
		Set:   true,
	}
}

// OptInt32 is optional int32.
type OptInt32 struct {
	Value int32
	Set   bool
}

// IsSet returns true if OptInt32 was set.
func (o OptInt32) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt32) Reset() {
	var v int32
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt32) SetTo(v int32) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt32) Get() (v int32, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt32) Or(d int32) int32 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt64 returns new OptInt64 with value set to v.
func NewOptInt64(v int64) OptInt64 {
	return OptInt64{
		Value: v,
		Set:   true,
	}
}

// OptInt64 is optional int64.
type OptInt64 struct {
	Value int64
	Set   bool
}

// IsSet returns true if OptInt64 was set.
func (o OptInt64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt64) Reset() {
	var v int64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt64) SetTo(v int64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt64) Get() (v int64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt64) Or(d int64) int64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilString returns new OptNilString with value set to v.
func NewOptNilString(v string) OptNilString {
	return OptNilString{
		Value: v,
		Set:   true,
	}
}

// OptNilString is optional nullable string.
type OptNilString struct {
	Value string
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilString was set.
func (o OptNilString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilString) Reset() {
	var v string
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilString) SetTo(v string) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilString) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilString) SetToNull() {
	o.Set = true
	o.Null = true
	var v string
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilString) Get() (v string, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

type SearchMessagesBadRequest Error

func (*SearchMessagesBadRequest) searchMessagesRes() {}

type SearchMessagesInternalServerError Error

func (*SearchMessagesInternalServerError) searchMessagesRes() {}

// Ref: #/components/schemas/SearchRequest
type SearchRequest struct {
	// Search keyword.
	Q string `json:"q"`
	// Web chat id (stringified int64).
	InsID string   `json:"ins_id"`
	Page  int32    `json:"page"`
	Limit OptInt32 `json:"limit"`
}

// GetQ returns the value of Q.
func (s *SearchRequest) GetQ() string {
	return s.Q
}

// GetInsID returns the value of InsID.
func (s *SearchRequest) GetInsID() string {
	return s.InsID
}

// GetPage returns the value of Page.
func (s *SearchRequest) GetPage() int32 {
	return s.Page
}

// GetLimit returns the value of Limit.
func (s *SearchRequest) GetLimit() OptInt32 {
	return s.Limit
}

// SetQ sets the value of Q.
func (s *SearchRequest) SetQ(val string) {
	s.Q = val
}

// SetInsID sets the value of InsID.
func (s *SearchRequest) SetInsID(val string) {
	s.InsID = val
}

// SetPage sets the value of Page.
func (s *SearchRequest) SetPage(val int32) {
	s.Page = val
}

// SetLimit sets the value of Limit.
func (s *SearchRequest) SetLimit(val OptInt32) {
	s.Limit = val
}

// Ref: #/components/schemas/SearchResult
type SearchResult struct {
	Hits               []MeiliMsg `json:"hits"`
	Query              string     `json:"query"`
	ProcessingTimeMs   int32      `json:"processingTimeMs"`
	Limit              int32      `json:"limit"`
	Offset             int32      `json:"offset"`
	EstimatedTotalHits int32      `json:"estimatedTotalHits"`
}

// GetHits returns the value of Hits.
func (s *SearchResult) GetHits() []MeiliMsg {
	return s.Hits
}

// GetQuery returns the value of Query.
func (s *SearchResult) GetQuery() string {
	return s.Query
}

// GetProcessingTimeMs returns the value of ProcessingTimeMs.
func (s *SearchResult) GetProcessingTimeMs() int32 {
	return s.ProcessingTimeMs
}

// GetLimit returns the value of Limit.
func (s *SearchResult) GetLimit() int32 {
	return s.Limit
}

// GetOffset returns the value of Offset.
func (s *SearchResult) GetOffset() int32 {
	return s.Offset
}

// GetEstimatedTotalHits returns the value of EstimatedTotalHits.
func (s *SearchResult) GetEstimatedTotalHits() int32 {
	return s.EstimatedTotalHits
}

// SetHits sets the value of Hits.
func (s *SearchResult) SetHits(val []MeiliMsg) {
	s.Hits = val
}

// SetQuery sets the value of Query.
func (s *SearchResult) SetQuery(val string) {
	s.Query = val
}

// SetProcessingTimeMs sets the value of ProcessingTimeMs.
func (s *SearchResult) SetProcessingTimeMs(val int32) {
	s.ProcessingTimeMs = val
}

// SetLimit sets the value of Limit.
func (s *SearchResult) SetLimit(val int32) {
	s.Limit = val
}

// SetOffset sets the value of Offset.
func (s *SearchResult) SetOffset(val int32) {
	s.Offset = val
}

// SetEstimatedTotalHits sets the value of EstimatedTotalHits.
func (s *SearchResult) SetEstimatedTotalHits(val int32) {
	s.EstimatedTotalHits = val
}

func (*SearchResult) searchMessagesRes() {}

type TgAuth struct {
	APIKey string
	Roles  []string
}

// GetAPIKey returns the value of APIKey.
func (s *TgAuth) GetAPIKey() string {
	return s.APIKey
}

// GetRoles returns the value of Roles.
func (s *TgAuth) GetRoles() []string {
	return s.Roles
}

// SetAPIKey sets the value of APIKey.
func (s *TgAuth) SetAPIKey(val string) {
	s.APIKey = val
}

// SetRoles sets the value of Roles.
func (s *TgAuth) SetRoles(val []string) {
	s.Roles = val
}

// Ref: #/components/schemas/UserInfo
type UserInfo struct {
	ID       int64        `json:"id"`
	Name     string       `json:"name"`
	Username OptNilString `json:"username"`
	Error    OptNilString `json:"error"`
}

// GetID returns the value of ID.
func (s *UserInfo) GetID() int64 {
	return s.ID
}

// GetName returns the value of Name.
func (s *UserInfo) GetName() string {
	return s.Name
}

// GetUsername returns the value of Username.
func (s *UserInfo) GetUsername() OptNilString {
	return s.Username
}

// GetError returns the value of Error.
func (s *UserInfo) GetError() OptNilString {
	return s.Error
}

// SetID sets the value of ID.
func (s *UserInfo) SetID(val int64) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *UserInfo) SetName(val string) {
	s.Name = val
}

// SetUsername sets the value of Username.
func (s *UserInfo) SetUsername(val OptNilString) {
	s.Username = val
}

// SetError sets the value of Error.
func (s *UserInfo) SetError(val OptNilString) {
	s.Error = val
}

// Ref: #/components/schemas/UserInfoRequest
type UserInfoRequest struct {
	UserIds []int64 `json:"user_ids"`
}

// GetUserIds returns the value of UserIds.
func (s *UserInfoRequest) GetUserIds() []int64 {
	return s.UserIds
}

// SetUserIds sets the value of UserIds.
func (s *UserInfoRequest) SetUserIds(val []int64) {
	s.UserIds = val
}

// Ref: #/components/schemas/UserInfoResponse
type UserInfoResponse struct {
	Users []UserInfo `json:"users"`
}

// GetUsers returns the value of Users.
func (s *UserInfoResponse) GetUsers() []UserInfo {
	return s.Users
}

// SetUsers sets the value of Users.
func (s *UserInfoResponse) SetUsers(val []UserInfo) {
	s.Users = val
}

func (*UserInfoResponse) getUsersInfoRes() {}
