-- encoding: utf-8
CREATE TABLE IF NOT EXISTS bili_inline_results
(
    uid     INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    text    TEXT    NOT NULL DEFAULT '',
    chat_id INTEGER NOT NULL DEFAULT 0,
    msg_id  INTEGER NOT NULL DEFAULT 0
) WITHOUT ROWID;